foglamp/FogLAMP

- src/python/Makefile
- src/python/build.sh
FOGL-83
run `make help` to see usage
`build.sh -c` calls `make clean`
> adding makefile for cleanup; added its use in build.sh

- src/python/.gitignore
- src/python/.pylintrc
- src/python/Makefile
- src/python/build.sh
- src/python/tox.ini
- FOGL-110: added pylint config file; 
- FOGL-107: fix warning with tox testenv; 
- FOGL-70: 1)  Fix TODO in linter
> FOGL-110, 107 pylint config; other fixes and improvements

- .gitignore
- Jenkinsfile
- docs/check_sphinx.py
- src/python/.gitignore
- src/python/requirements.txt
- src/python/tests/test_db_config.py
- src/python/tox.ini
[FOGL-67](https://scaledb.atlassian.net/browse/FOGL-67) - Jenkins Pipeline script
1. Allure-report Plugin - For allure report
2. ANSI-Color Plugin - For beautification of log statements as a colorful
3. Github-Plugin - To all GitHub setup
4. Warnings-Plugin - For Pylint checkers/violation
**Added:** allure cli installer in Manage Jenkins > Global tools configuration
`sudo apt install python3.5 python3-pip virtualenv`
> FOGL-67 add a Jenkinsfile

- Jenkinsfile
- src/python/Makefile
- src/python/build.sh
[FOGL-158](https://scaledb.atlassian.net/browse/FOGL-158)
[FOGL-154](https://scaledb.atlassian.net/browse/FOGL-154)
> Fogl-158 - rename doctest to doc-build-test or test-doc-build

- Jenkinsfile
[FOGL-159](https://scaledb.atlassian.net/browse/FOGL-159)
> default branch name changed to develop in Jenkinsfile

- docs/conf.py
- src/python/Makefile
- src/python/requirements-doc.txt
[FOGL-216](https://scaledb.atlassian.net/browse/FOGL-216) - Use readthedocs theme
Fixed items:
1) sphinx_rtd_theme added
2) missing targets info added in Makefile
- See attached screenshot
> FOGL-216 - Use readthedocs theme

- src/python/foglamp/configuration_manager.py
- src/python/foglamp/logger.py
**LEVELS:**  warn to exception
**address:**  
- /dev/log for Linux 
**In Ubuntu**, you can see syslogs using System Log app.
Log file: `/var/log/syslog`
`tail -f /var/log/syslog` to monitor logs
> FOGL-203 the simplest syslog logging system

- src/python/foglamp/core/api.py
- src/python/foglamp/core/routes.py
[FOGL-219](https://scaledb.atlassian.net/browse/FOGL-219) - Build the Configuration REST API
**How to run?**
1) install requirements.txt  or "source build.sh -i" or "source build.sh -a " and make install
2) start core service "python -m foglamp.core" or just foglamp start
3) Import collection and use configuration_manager environment  in postman and run the stuff with given or other test values.
4) for #3 you can use Curl too
-PFA
[collection.zip](https://github.com/foglamp/FogLAMP/files/1160328/collection.zip)
> FOGL-219 Configuration manager REST API

- src/python/__template__.py
> FOGL-41 Add to __template__.py

- src/python/foglamp/core/browser.py
- src/python/foglamp/core/routes.py
- src/python/requirements.txt
Initial implementation of a user api to browse readings data as required for mid-August demo
> FOGL-311 Initial commit of data browser for mid-August demo

- src/python/foglamp/statistics.py
- src/sql/foglamp_ddl.sql
- src/sql/foglamp_init_data.sql
this is to be used by components to update metric values
> FOGL-327 added method to update statistics, schema change

- src/python/foglamp/update_statistics_history.py
This will allow restapi to properly retrieve "groups" of statistics.
> FOGL-344 history_ts for a group of statistics should be the same

- src/python/foglamp/device/coap/controller.py
@Terris-Dianomic - Where would the `uri` and `port` be utilized in code? 
Please **do not** accept to merge yet, as this is a work in progress.
> FOGL-337: Implementation of configuration as part of the CoAP process

- src/python/foglamp/translators/omf_translator.py
Stefano will complete the work and put the rest of the configuration in
> FOGL-343 base work is for config manager omf translator integration is done

- src/sql/foglamp_init_data.sql
@sstefano69 is it necessary to add these lines to init:
INSERT INTO foglamp.destinations(id,description, ts) VALUES (1,'OMF', now());
INSERT INTO foglamp.streams(id,destination_id,description, last_object,ts) VALUES (1,1,'OMF', 1,now());
> FOGL-316 added omf translator as scheduled task - every 15 seconds

- docs/source/foglamp.core.rst
- docs/source/foglamp.rst
- src/python/foglamp/core/scheduler.py
- src/python/foglamp/core/server.py
- src/python/foglamp/logger.py
- src/python/tests/core/test_scheduler.py
Please see the test for example usage. The API is documented in the scheduler architecture document.
> FOGL-269 Scheduler bug fixes, refactoring, and API methods

- src/python/foglamp/translators/README.rst
- src/python/foglamp/translators/omf_translator.py
- src/sql/foglamp_init_data.sql
- send_omf_message_to_end_point changed 
- performance trk as debug using - omf_translator_perf as
> Fogl 366 - 1 OMF message for the block size / other improvements

- src/python/foglamp/core/routes.py
Not able to start **core services** because of incomplete code removal  commit https://github.com/foglamp/FogLAMP/pull/116/commits/9ad8875e054c6d449bd15f617bb07a9950105e3d
> removed route binding for get_tasks_running

- benchmarks/fogbench/__main__.py
other in queue are #118 and #123
> host and port as arg

- benchmarks/fogbench/__main__.py
- src/python/foglamp/device/coap/controller.py
- src/python/foglamp/device/coap/sensor_values.py
> Fogbench remove prints and sensor value chnages

- src/python/foglamp/core/api/audit.py
- src/python/foglamp/core/api/audit_trail_db_services.py
- src/python/foglamp/core/api/browser.py
- src/python/foglamp/core/api/scheduler.py
- src/python/foglamp/core/api/statistics.py
- src/python/foglamp/core/api/statistics_db_services.py
- src/python/foglamp/core/routes.py
Items:
-------------------------------------------------------------------------------------------
`[ {index: 1, state:"blah"}, {index: 2, state:"blah2"}... ] ` as used in scheduler module.
same for schedule type.
> REST API fixes

- src/python/foglamp/data_purge/purge.py
After pushing in, it was found that in certain cases, the tests fail. This change of having an if/else at one point is suppose to fix it.
> FOGL-430B: Change connection pool size and close connection after execution in purge process

- src/python/foglamp/configuration_manager.py
- src/python/foglamp/core/api/audit_trail_db_services.py
- src/python/foglamp/core/api/browser.py
- src/python/foglamp/core/api/scheduler_db_services.py
- src/python/foglamp/core/api/statistics_db_services.py
- src/python/foglamp/core/scheduler.py
- src/python/foglamp/data_purge/purge.py
- src/python/foglamp/device/coap/sensor_values.py
- src/python/foglamp/device/ingest.py
- src/python/foglamp/statistics.py
- src/python/foglamp/translators/omf_translator.py
- src/python/foglamp/translators/statistics_to_pi.py
- src/python/foglamp/update_statistics_history.py
- src/python/requirements.txt
explicitly state foglamp username on connection string, use snap's socket dir if available
everyone please review if your component is affected
> FOGL-506 db connection user change, socket dir use from snap

- Jenkinsfile
`H(0-0) 5,14 * * *`
Timezone | Run1       |Run2
---------- | -------- |---------
UTC          | 2:00PM  | 5:00AM
PDT           | 7:00AM | 10:00PM
IST            | 7:30PM | 10:30AM
> fixed time of ci-run as per UTC timezone

- src/python/foglamp/storage/payload_builder.py
complements https://github.com/foglamp/FogLAMP/pull/203
> tested and minor refactoring

- src/C/foglamp/common/include/json_provider.h
- src/C/foglamp/common/include/management_api.h
- src/C/foglamp/common/include/management_client.h
- src/C/foglamp/common/include/service_record.h
- src/C/foglamp/common/management_api.cpp
- src/C/foglamp/common/management_client.cpp
- src/C/foglamp/common/service_record.cpp
- src/C/foglamp/storage/include/storage_stats.h
- src/C/foglamp/storage/storage.cpp
- src/C/foglamp/storage/storage_api.cpp
- src/C/foglamp/storage/storage_stats.cpp
Added calls for registration and ping
> Fogl 197 - Add micro service management api/client

- src/python/foglamp/storage/storage.py
> Revert "return valid JSON"

- src/python/tests/test_configuration_manager.py
@oshadmon  please see this; now it does not matter init data is  there or not, or even if we play with dev DB; As we are deleting our created data only!
> FOGL-491 improvement

- src/python/foglamp/storage/__main__.py
- src/python/foglamp/storage/storage.py
> ping url and managment api checks (with TODO) added in client

- src/python/foglamp/storage/__main__.py
- src/python/foglamp/storage/payload_builder.py
- src/python/foglamp/storage/storage.py
enjoy with payload builder and storage client; allow few seconds to storage to register itself
> [FOGL-613] storage service discovery by name; start core then start start storage

- src/python/foglamp/storage/payload_builder.py
- src/python/tests/storage/test_payload_builder.py
- src/python/tests/storage/test_storage_api.py
@vaibhav-ScaleDB  please merge into the PR you have for tests to move forward. final cut will be provided post FOGL-582 ' PR merge
> [FOGL-607] limit, offset, default sort order and select all  payload fixes

- src/python/tests/storage/test_storage_api.py
**Test O/P:**
```
collected 30 items 
tests/storage/test_storage_api.py ....ss.....s.ss.ssss..s.......===== 20 passed, 10 skipped in 0.96 seconds
```
> test storage api tests fixes

- src/python/foglamp/core/server.py
- src/python/foglamp/device/__main__.py
- src/python/foglamp/storage/storage.py
- src/python/tests/storage/test_storage_api.py
…  also fixed the tests; provide mgt port at test execution time until we get this fixed
```
tests/storage/test_storage_api.py ................ssss..........
===================== 26 passed, 4 skipped in 7.28 seconds =====================
```
> FOGL-652 storage client fixes for storage service discovery with core mgt host and port;

- src/python/foglamp/device/ingest.py
* attempt only once, if unknown error/ exception
* if storage engine says, retry-able then try again 
* if no, just get put of loop
> FOGL-660 Error handing for Device service plugin ingest (FOGL-519)

- src/python/foglamp/core/api/audit.py
- src/python/foglamp/core/connect.py
- src/python/foglamp/storage/storage.py
**audit**
* - [x] /foglamp/audit
* - [x] /foglamp/audit/logcode
* - [x] /foglamp/audit/severity
> FOGL-645 audit with storage engine and allow global discovery in core process

- src/python/tests/data_purge/test_data_purge.py
Test added :
test_unsent_read_purge_within_age
Results:
10 passed in 2.95 seconds
> FOGL-667 : Add unit test to cover purge test scenario FOGL-666	

- Makefile
See comments in Makefile. 
typical use:
git clone https://github.com/foglamp/FogLAMP.git
cd FogLAMP
[sudo] make
[sudo] make install [DESTDIR=/some/absolute/path]
Note: for dev envs. we need a script to address FOGLAMP_ROOT, PYTHONPATH
> FOGL-720 added install target, refined based on clarifications

- python/foglamp/common/storage_client/storage_client.py
- python/foglamp/services/core/api/audit.py
[FOGL-714](https://scaledb.atlassian.net/browse/FOGL-714)
> FOGL-714 fixes for audit_log pagination

- python/foglamp/services/core/api/statistics.py
[FOGL-776](https://scaledb.atlassian.net/browse/FOGL-776)
curl -X GET http://localhost:8081/foglamp/statistics/history?limit=1
```
{
"statistics": [
{
"PURGED": 0,
"READINGS": 0,
"BUFFERED": 0,
"UNSNPURGED": 0,
"UNSENT": 0,
"SENT_1": 0,
"history_ts": "2017-11-29 16:30:39",
"DISCARDED": 0,
"SENT_2": 0
}
],
"interval": 5
}
```
> FOGL-776 remove hard-coded records per distinct for stats history endpoint

- python/foglamp/services/core/api/statistics.py
[FOGL-777](https://scaledb.atlassian.net/browse/FOGL-777) - interval in secs
>SELECT schedule_interval FROM schedules WHERE process_name='stats collector' ---- 00:00:15
curl -X GET http://localhost:8081/foglamp/statistics/history?limit=1
O/P:
```
{
"statistics": [
{
"UNSENT": 0,
"history_ts": "2017-11-29 18:12:06",
"DISCARDED": 0,
"SENT_2": 0,
"BUFFERED": 0,
"PURGED": 0,
"UNSNPURGED": 0,
"READINGS": 0,
"SENT_1": 0
}
],
"interval": 15
}
```
> FOGL-777 interval value in secs for stats history end point

- .gitignore
- tests/unit-tests/python/foglamp_test/services/core/api/test_statistics.py
(stats history test ~will be in new PR~ are in https://github.com/foglamp/FogLAMP/pull/343)
For this note the deviation https://docs.google.com/document/d/1JJDP7g25SWerNVCxgff02qp9msHbqA9nt3RAFx8-Qng/edit#heading=h.wxe1fbyc0ddz
but (there are 2 sent keys now; SENT_1 and SENT_2; and  all keys are upper-case) // see comments in doc and open the issue to fix mapping etc.
> FOGL-573 (Part 1) statistics test 

- python/foglamp/services/core/api/statistics.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_statistics_history.py
ugly! takes 45+ seconds once test db is there, will make better :]
```
tests/unit-tests/python/foglamp_test/services/core/api/test_statistics_history.py ...
========================== 3 passed in 45.30 seconds ===========================
```
> FOGL-573 (Part 2) statistics history REST api test; 

- python/foglamp/services/common/microservice.py
- python/foglamp/services/south/server.py
This bug is fixed but:
In the future, error handling/exception handling needs to be better in process.py microservice client code. This will be part of the work to complete microservice client code.
> FOGL-807 bug fix - south services registers with core

- python/foglamp/services/common/microservice_management/service_registry/monitor.py
- python/foglamp/services/core/server.py
- python/requirements.txt
820 and 812 need handling in new PR.
> FOGL-766 Investigate start/ stop console output and fix

- scripts/foglamp
Address these problems for the integration with the restore :
The current implementation of foglamp stop kills also the restore
The current implementation of foglamp stop returns an error
> FOGL-838_changed_Foglamp_stop

- C/plugins/storage/postgres/connection.cpp
- C/plugins/storage/postgres/include/connection.h
Allow insert without a readings key
Improve logging of database errors
Manage quotes in strings and JSON
> Fogl 662 Various storage related updates and fixes

- python/foglamp/plugins/storage/postgres/backup_restore/backup_postgres.py
- python/foglamp/plugins/storage/postgres/backup_restore/restore_postgres.py
Jira : FOGL-845 - Fix return from Backup.create_backup
> FOGL-845_bck_rest_fix_return - fix returns for create_backup and restore

- Makefile
- python/foglamp/plugins/storage/postgres/backup_restore/backup_postgres.py
- python/foglamp/plugins/storage/postgres/backup_restore/exceptions.py
- python/foglamp/plugins/storage/postgres/backup_restore/restore_postgres.py
handing of the Deploy environment
> Fogl 854 bck rest deploy env

- python/foglamp/services/core/service_registry/monitor.py
**curl -X GET http://localhost:42827/foglamp/service**
```
{"services": [{"address": "localhost", "name": "FogLAMP Storage", "id": "3757ba3b-ab6c-4b11-bbfa-2db39478a852", "protocol": "http", "status": 1, "management_port": 40073, "type": "Storage", "service_port": 44437}, {"address": "0.0.0.0", "name": "FogLAMP Core", "id": "2a69f502-cd1f-492e-ae25-6744704d3dfb", "protocol": "http", "status": 1, "management_port": 42827, "type": "Core", "service_port": 8081}, {"address": "0.0.0.0", "name": "COAP", "id": "1dd2585d-6a91-4200-8b53-245e07a7db63", "protocol": "http", "status": 1, "management_port": 39235, "type": "Southbound", "service_port": 39235}, {"address": "0.0.0.0", "name": "CC2650POLL", "id": "9cf55198-e10c-4d8a-8b39-6a45f2205ddd", "protocol": "http", "status": 1, "management_port": …
```
> FOGL-914 make a number of attempts to ping before unregistering a service during monitoring

- python/foglamp/common/microservice_management_client.py
- python/foglamp/common/microservice_management_client/exceptions.py
- python/foglamp/common/microservice_management_client/microservice_management_client.py
- python/foglamp/common/process.py
- python/foglamp/services/common/microservice.py
created reusable class for a microservice_management_client 
process.py now uses this class to connect to core
> FOGL-904 microservicement management client

- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/api/statistics.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_task.py
**NOTE:** No regression as such with new changes. Below are the tests result. Some tests are failing as they were before, does not have proper clean up yet
**O/P**
```
test_scheduler.py
collected 10 items 
test_scheduler.py::TestScheduler::test_get_scheduled_processes Starting FogLAMP...............
FogLAMP started.
PASSED
test_scheduler.py::TestScheduler::test_get_scheduled_process PASSED
test_scheduler.py::TestScheduler::test_post_schedule PASSED
test_scheduler.py::TestScheduler::test_update_schedule PASSED
test_scheduler.py::TestScheduler::test_delete_schedule PASSED
test_scheduler.py::TestScheduler::test_get_schedule PASSED
test_scheduler.py::TestScheduler::test_get_schedules PASSED
test_scheduler.py::TestScheduler::test_start_schedule FAILED …
```
> FOGL-858 (Part-2) scheduler core api error handling fixes with negative tests

- python/foglamp/plugins/north/common/common.py
- python/foglamp/plugins/north/omf/omf.py
- python/foglamp/tasks/north/sending_process.py
- tests/unit-tests/python/foglamp_test/plugins/north/common/test_common.py
it addresses the problem of having OMF translator handle numbers in string format
> Fogl 934 - it addresses the problem of having OMF translator handle numbers in string format

- python/foglamp/tasks/north/sending_process.py
fixed :
_log_debug_level parameter handling
performance logging handling
some comments
> FOGL-952_sending process bug fix

- python/foglamp/plugins/south/http_south/http_south.py
How to test:
1) set HTTP south plugin enabled in init.sql
2) start foglamp
3) note mgt port of HTTP south plugin from `http://localhost:<core port>/foglamp/service`
4) call `http://localhost:<mgt port of south plugin>/foglamp/service/shutdown`
5) no error (like generator has no wait closed ...) should be there in syslog, HTTP south must shutdown gracefully.
6) verify via ps -ef and `http://localhost:<core port>/foglamp/service`
> FOGL-954 fix server generator coroutine issue

- tests/unit/python/foglamp/services/core/test_main.py
it was tricky to test main entry point!
> FOGL-1024 unit tests for services/core/__main__.py 

- python/foglamp/common/audit_logger.py
- python/foglamp/services/core/server.py
- python/foglamp/services/south/server.py
- tests/unit/python/foglamp/common/test_audit_logger.py
exception handling fixes, 
using event loop fixture for test; 
other minor miss fixes
> 701 exception handling fixes

- python/foglamp/common/statistics.py
**NOTE** - pending code coverage unit tests will cover in https://scaledb.atlassian.net/browse/FOGL-1096
> FOGL-1097 unresolved references fixes for stats

- docs/03_getting_started.rst
- docs/04_installation.rst
- docs/05_testing.rst
- docs/06_plugins.rst
- docs/07_admin/02_utilities.rst
@MarkRiddoch - Looking at you doc and the output from the rest API, things are slightly different - could you pls have a look? 
Specifically:
05_testing.html#the-omf-translator >>> $ curl -s http://localhost:8081/foglamp/schedule
vs.
https://docs.google.com/document/d/1JJDP7g25SWerNVCxgff02qp9msHbqA9nt3RAFx8-Qng/edit#heading=h.daqvxnnb7r5s
@sstefano69 - pls have a look at the same page for the example regarding SEND_PR_1.
> FOGL-941 - Updated doc

- python/foglamp/common/jqfilter.py
- tests/unit/python/foglamp/common/test_jqfilter.py
- Test Results:
`4 passed in 0.04 seconds`
- Code coverage:
```
Coverage for /FogLAMP/python/foglamp/common/jqfilter.py : 100% 
19 statements   19 run 0 missing 0 excluded
```
> FOGL-1066: Unit test for jqfilter.py

- extras/python/fogbench/__main__.py
> FOGL-765.a 

- .gitignore
@MarkRiddoch I think we should ignore `data/var` directory
> "data/var" directory ignored

- python/foglamp/tasks/statistics/statistics_history.py
- tests/unit/python/foglamp/tasks/statistics/test_statistics_history.py
- Test Results
```
6 passed in 0.47 seconds
```
- Test Coverage
```
Coverage for /FogLAMP/python/foglamp/tasks/statistics/statistics_history.py : 100%
40 statements   40 run 0 missing 0 excluded
```
> FOGL-1013 Unit test for statistics_history

- tests/unit/python/foglamp/services/core/api/test_browser_assets.py
```
Coverage for /home/foglamp/Development/FogLAMP/python/foglamp/services/core/api/browser.py : 88%
182 statements  -- 161 run | 21 missing | 0 excluded
```
```
collected 23 items                                                                                                                            
services/core/api/test_browser_assets.py::TestBrowserAssets::test_routes_count PASSED
services/core/api/test_browser_assets.py::TestBrowserAssets::test_routes_info PASSED
services/core/api/test_browser_assets.py::TestBrowserAssets::test_end_points[pyloop-foglamp/asset-{"aggregate": {"column": "*", "alias": "count", "operation": "count"}, "group": "asset_code"}-result0] PASSED
services/core/api/test_browser_assets.py::TestBrowserAssets::test_end_points[pyloop-/foglamp/asset/fogbench%2fhumidi …
```
> FOGL-1008 unit tests added for browser.py

- python/foglamp/common/audit_logger.py
- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/update.py
- tests/unit/python/foglamp/services/core/api/test_audit.py
**test results:**
`================================================== 324 passed, 1 skipped in 6.51 seconds ==================================================`
> removed eval usage; and consistent severity level 

- tests/unit/python/foglamp/plugins/south/test_http_south.py
**Tests O/P**
```
collected 3 items                                                                                                                             
plugins/south/test_http_south.py::TestHttpSouthIngest::test_post_sensor_reading_ok PASSED
plugins/south/test_http_south.py::TestHttpSouthIngest::test_post_sensor_reading_missing_delimiter PASSED
plugins/south/test_http_south.py::TestHttpSouthIngest::test_post_sensor_reading_not_dict PASSED
=== 3 passed in 0.11 seconds ==
```
**total**
```
collected 402 items                                                                                                                           
common/test_audit_logger.py ..........                                                                                                  [  2%] …
```
> http_south fixes as per FOGL-765, 1084 changes

- python/foglamp/services/core/api/statistics.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
```
tests/unit/python/foglamp/services/core/api/test_statistics_api.py::TestStatistics::test_get_stats[pyloop] PASSED
tests/unit/python/foglamp/services/core/api/test_statistics_api.py::TestStatistics::test_get_stats_exception[pyloop] PASSED
tests/unit/python/foglamp/services/core/api/test_statistics_api.py::TestStatistics::test_get_statistics_history[pyloop] PASSED
tests/unit/python/foglamp/services/core/api/test_statistics_api.py::TestStatistics::test_get_statistics_history_limit[pyloop] PASSED
tests/unit/python/foglamp/services/core/api/test_statistics_api.py::TestStatistics::test_get_statistics_history_bad_limit[pyloop--1] PASSED
tests/unit/python/foglamp/services/core/api/test_statistics_api.py::TestStatistics::test_get_statistics_history_bad_limit[pyloop-blah] PASSED …
```
> FOGL-1011 statistics api test

- python/foglamp/services/core/api/common.py
- tests/unit/python/foglamp/services/core/api/test_common_ping.py
tested with curl from local and remote machines!
> FOGL-1012 admin rest api shutdown test added with loop fix

- python/foglamp/common/web/middleware.py
- tests/unit/python/foglamp/common/web/middleware.py
- tests/unit/python/foglamp/common/web/test_middleware.py
**Test Result:**
```
collected 6 items                                                                                                                         
tests/unit/python/foglamp/common/web/middleware.py .....                                                                            [100%]
======================================================== 6 passed in 0.30 seconds =========================================================
```
**Coverage:**
```
Name                                                   Stmts   Miss  Cover
----------------------------------------------------------------------------
foglamp/common/web/test_middleware.py                         67      0   100%
```
**Total:**
================================================= 471 passed, 1 skipped in 18.18 seconds …
> FOGL-1060 middleware tests added with refactoring

- tests/unit/python/foglamp/services/core/api/test_scheduler_api.py
**suite** -- All Good
```
collected 592 items 
= 590 passed, 1 skipped, 1 xfailed in 28.13 seconds ==
```
**Scheduler tests**
```
collected 78 items
= 77 passed, 1 xfailed in 3.14 seconds ==
```
> FOGL-1010 - tear down fixes for scheduler api tests (unit test fixes)

- tests/system/tests/bash/pi_delete.bash
- tests/system/tests/bash/pi_delete.desc
the script will not be automatically executed but it will remain ready for a possible use.
> FOGL-1116:  pi_delete.bash added to the end_to_end_PI test suite

- C/plugins/storage/postgres/init.sql
FOGL-1147: foglamp.version table creation moved into DDL section
> FOGL-1147: foglamp.version table creation moved into DDL section

- scripts/common/json_parse.py
- scripts/foglamp
Tested in :
* develop - Ubuntu server Vbox
* deploy - Ubuntu server Vbox
* snap - Ubuntu core VBOX
it is available a test script in :
https://github.com/sstefano69/dianomic-test/blob/master/task/FOGL-1149/test_foglamp.sh
> Fogl 1149 - foglamp script uses the pid

- python/foglamp/services/core/api/statistics.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
**json_response**
```
{
"interval": 15,
"statistics": [
{
"SENT_4": 0,
"SENT_3": 0,
"UNSNPURGED": 0,
"FOGBENCH/WALL CLOCK": 0,
"FOGBENCH/LUXOMETER": 0,
"FOGBENCH/SWITCH": 0,
"SENT_2": 0,
"SENT_1": 0,
"PURGED": 0,
"FOGBENCH/MAGNETOMETER": 0,
"FOGBENCH/TEMPERATURE": 0,
"FOGBENCH/ACCELEROMETER": 0,
"READINGS": 0,
"FOGBENCH/GYROSCOPE": 0,
"DISCARDED": 0,
"history_ts": "2018-03-06 11:56:55",
"FOGBENCH/PRESSURE": 0,
"FOGBENCH/MOUSE": 0,
"BUFFERED": 0,
"FOGBENCH/HUMIDITY": 0,
"UNSENT": 0
},
{
"SENT_4": 0,
"UNSNPURGED": 0,
"FOGBENCH/LUXOMETER": 0,
"FOGBENCH/SWITCH": 0,
"SENT_2": 0,
"PURGED": 0,
"FOGBENCH/MAGNETOMETER": 0,
"READINGS": 0,
"SENT_1": 0,
"history_ts": "2018-03-06 11:56:40",
"FOGBENCH/TEMPERATURE": 0,
"FOGBENCH/WALL CLOCK": 0,
"SENT_3": 0,
"FOGBENCH/ACCELEROMETER": 0, …
```
> FOGL-1145 fixed sort order on history ts for stats history

- .gitignore
- python/foglamp/services/core/api/support.py
- python/foglamp/services/core/support.py
- python/foglamp/services/core/syslog_parser.py
- tests/unit/python/foglamp/services/core/api/test_support.py
Test result:
`============================================= 702 passed, 10 skipped in 32.04 seconds ==============================================
`
> Fogl 1126 - Create support bundle

- tests/unit/python/foglamp/services/core/api/test_support.py
```
collected 732 items
== 722 passed, 10 skipped in 38.29 seconds ====
```
> import fixes  for test_support.py

- python/foglamp/tasks/purge/purge.py
- tests/unit/python/foglamp/tasks/purge/test_purge.py
> FOGL-1165: Fix purge.py code to handle storage error

- python/foglamp/services/core/api/support.py
- tests/unit/python/foglamp/services/core/api/test_support.py
**unit test results:**
`================================================= 722 passed, 10 skipped in 34.35 seconds =================================================`
> FOGL-1175 allow support bundle to download

- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/routes.py
- python/foglamp/services/core/user_model.py
- scripts/plugins/storage/postgres/init.sql
> update with storage and enabled column added for users table

- python/foglamp/common/web/middleware.py
- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/user_model.py
- tests/unit/python/foglamp/services/core/test_user_model.py
```
collected 795
=== 783 passed, 12 skipped in 42.45 seconds ==
```
> Logs added to middleware and user admin API

- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/routes.py
- python/foglamp/services/core/user_model.py
- tests/unit/python/foglamp/services/core/test_user_model.py
`791 passed, 12 skipped in 45.65 seconds `
> FOGL-1194 token based logout and logout for all active sessions for self or admin

- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/user_model.py
- tests/unit/python/foglamp/services/core/api/test_auth_optional.py
From #659 
Code Coverage **91%**
```
235 statements   213 run 22 missing 0 excluded
```
**TestAuthOptional tests**
```
collected 78 items                                                                                                                            
== 78 passed in 4.40 seconds ==
```
> FOGL-1188 auth optional tests added with TODO comments

- python/foglamp/services/core/api/backup_restore.py
- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
Coverage for backup_restore.py : **100%** 
```
115 statements   115 run 0 missing 0 excluded
```
test_backup_restore.py
```
collected 38 items
== 38 passed in 1.98 seconds ==
```
Suite
```
collected 889 items
== 877 passed, 12 skipped in 47.34 seconds ==
```
> restore test fixes after the merge of PR#652

- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/user_model.py
- tests/unit/python/foglamp/services/core/api/test_auth_optional.py
- tests/unit/python/foglamp/services/core/test_user_model.py
**test_auth_optional.py**
```
collected 78 items
= 78 passed in 3.16 seconds ==
```
**test_user_model.py**
```
collected 40 items
== 39 passed, 1 skipped in 0.25 seconds ===
```
> FOGL-1190 Soft delete the user in user management 

- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/api/support.py
- python/foglamp/services/core/support.py
- tests/unit/python/foglamp/services/core/api/test_support.py
Test result:
> ============================================= 877 passed, 12 skipped in 41.53 seconds ==============================================
> FOGL-1208-1210 - fixed auth error in support bundle creation + offset error in fetching syslog

- python/foglamp/plugins/storage/postgres/backup_restore/restore_postgres.py
> FOGL-1223: restore fixed in relation to the 'foglamp status'

- python/foglamp/tasks/north/sending_process.py
FOGL-1154: fixed Python code style
> FOGL-1154: fixed Python code style

- python/foglamp/common/web/middleware.py
- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/routes.py
- python/foglamp/services/core/user_model.py
**NOTE** -- will update tests once approved :)
> Admin API end point added for user reset role and password

- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
> FOGL-1233 add config item REST  end-point added

- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/common/microservice_management_client/test_microservice_management_client.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
- tests/unit/python/foglamp/services/core/api/test_server.py
Test suite results:
`
============= 939 passed, 12 skipped in 56.54 seconds ================`
> FOGL-1232: unit tests for core API and micro-service management client for configuration management

- Makefile
> FOGL-1252 no-cache-dir flag added for python-requirement target with/out user

- python/foglamp/services/core/api/service.py
- tests/unit/python/foglamp/services/core/api/test_service.py
**Code Coverage 100%** 
`73 statements   73 run 0 missing 0 excluded`
**Tests O/P**
`=== 960 passed, 12 skipped in 51.13 seconds ===`
> FOGL-1122 Tests added for service.py

- python/foglamp/plugins/storage/postgres/backup_restore/exceptions.py
- python/foglamp/plugins/storage/postgres/backup_restore/lib.py
the code switch to use the storage exececutable instead of the foglamp.json to evaluate if the plugin is managed or not.
> Fogl 1253 - fix the Back up process

- tests/unit/python/foglamp/plugins/north/omf/test_omf.py
Ready to be reviewed and eventually merged.
> Fogl 1271: unit test for OMF

- tests/unit/python/foglamp/tasks/north/test_sending_process.py
Ready to be reviewed and eventually merged.
> Fogl 1259 - unit test for SendingProcess

- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/test_scheduler_api.py
1. Bug fixed
2. Unit tests fixed (All unit tests pass)
> FOGL-1279: Task cancel URL is incorrect in API

- tests/unit/python/foglamp/tasks/north/test_sending_process.py
{code}
foglamp@ubuntu:~/Development/FogLAMP/tests/unit/python/foglamp$ cd /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/;time pytest -v | grep test_sending_process
tasks/north/test_sending_process.py::TestSendingProcess::test_send_data_block[10-20-10] PASSED [ 96%]
tasks/north/test_sending_process.py::TestSendingProcess::test_standard_plugins[empty-north-Empty North Plugin] PASSED [ 96%]
tasks/north/test_sending_process.py::TestSendingProcess::test_standard_plugins[omf-north-OMF North] PASSED [ 97%]
tasks/north/test_sending_process.py::TestSendingProcess::test_standard_plugins[ocs-north-OCS North] PASSED [ 97%]
tasks/north/test_sending_process.py::TestSendingProcess::test_standard_plugins[http_north-north-http_north] PASSED [ 97%] …
> FOGL-1285: fix SendingProcess unit tests

- tests/unit/python/foglamp/plugins/north/common/test_common.py
```
======== 2 failed, 1047 passed, 34 skipped in 61.15 seconds =========
```
```
foglamp@ubuntu:~/Development/FogLAMP/tests/unit/python/foglamp/plugins/north/common$ pytest -v
========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
rootdir: /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/plugins/north/common, inifile:
collected 50 items
test_common.py::TestPluginsNorthCommon::test_convert_to_type_good[xxx-xx …
```
> Fogl 1281: unit test for plugins/north/common

- python/foglamp/common/configuration_manager.py
- python/foglamp/common/storage_client/payload_builder.py
- python/foglamp/plugins/storage/postgres/backup_restore/backup_postgres.py
- python/foglamp/plugins/storage/postgres/backup_restore/lib.py
- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/browser.py
- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/api/statistics.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/core/user_model.py
- tests/unit/python/foglamp/common/storage_client/test_payload_builder.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/services/core/api/test_browser_assets.py
`=================================================== 1086 passed, 13 skipped in 48.10 seconds ====================================================
`
> FOGL 637/640/643 - Provide "ALIAS" support in Payload builder + json type support + TODO removal

- tests/system/suites/end_to_end_OCS/e/0060_read_from_REST.expected
- tests/system/suites/end_to_end_PI/e/0060_read_from_REST.expected
- tests/system/suites/smoke/e/005_read_from_REST.expected
*Smoke*
```
foglamp@nerd-034:~/Development/FogLAMP/tests/system/suites$ ./foglamp-test smoke
Script Suite:     smoke
Suite DIR:        /home/foglamp/Development/FogLAMP/tests/system/suites/smoke
Test DIR:         /home/foglamp/Development/FogLAMP/tests/system/tests
FogLAMP Root:     /home/foglamp/Development/FogLAMP
FogLAMP Data:     
foglamp command:  /home/foglamp/Development/FogLAMP/scripts/foglamp
fogbench command: /home/foglamp/Development/FogLAMP/scripts/extras/fogbench
Suite Start: 2018-05-01 12:37:36.083185
[2018-05-01 12:37:36.092114] - 001_prepare - [2018-05-01 12:38:09.737520] (33.638 seconds) - PASSED
[2018-05-01 12:38:09.745903] - 002_start - [2018-05-01 12:38:17.506509] (7.756 seconds) - PASSED
[2018-05-01 12:38:17.513197] - 003_inject - [2018-05-01 12:38:17.816545] (.298 …
```
> asset_code key changed to assetCode in system tests

- scripts/foglamp
TBD Documentation needs updating
> Fogl 1191 - Add username and password handling to foglamp script

- tests/unit/python/foglamp/tasks/north/test_sending_process.py
**Stand alone execution**
```javascript
test_sending_process.py::TestSendingProcess::test_load_data_into_memory_audit PASSED                             [ 84%]
test_sending_process.py::TestSendingProcess::test_send_data_good[3-1-False-3-3] PASSED                           [ 86%]
test_sending_process.py::TestSendingProcess::test_send_data_good[3-1-True-3-3] PASSED                            [ 88%]
test_sending_process.py::TestSendingProcess::test_send_data_stop_exec PASSED                                     [ 90%]
test_sending_process.py::TestSendingProcess::test_retrieve_configuration_good[p_config0-expected_config0] PASSED [ 92%]
test_sending_process.py::TestSendingProcess::test__start_stream_not_valid PASSED                                 [ 94%] …
```
> Fogl 1291: Phase 1: Extend unit tests for SendingProcess

- python/foglamp/common/storage_client/payload_builder.py
- tests/unit/python/foglamp/common/storage_client/data/payload_timebucket1.json
- tests/unit/python/foglamp/common/storage_client/data/payload_timebucket2.json
- tests/unit/python/foglamp/common/storage_client/data/payload_timebucket3.json
- tests/unit/python/foglamp/common/storage_client/test_payload_builder.py
Test result:
`=================================================== 1110 passed, 13 skipped in 51.43 seconds ====================================================
`
> FOGL-641 - Timebucket support added to Payload Builder

- tests/unit/python/foglamp/common/storage_client/data/payload_timebucket4.json
- tests/unit/python/foglamp/common/storage_client/test_payload_builder.py
`=== 1193 passed, 13 skipped in 66.30 seconds ===`
> timebucket4 data missing file added

- tests/unit/python/foglamp/common/test_statistics.py
```
Coverage for /FogLAMP/python/foglamp/common/statistics.py : 100% 
67 statements   67 run 0 missing 0 excluded
```
Test suite results:
```
=== 1195 passed, 13 skipped in 64.16 seconds ===
```
> FOGL-1096: Cover pending code coverage for "common/statistics.py"

- python/foglamp/services/core/scheduler/scheduler.py
- To test this PR, please follow steps of [FOGL-1340](https://scaledb.atlassian.net/browse/FOGL-1340). Better to do a "foglamp reset" also before starting foglamp server in order to have clean state of the DB. Proper setting of FOGLAMP_ROOT env var is essential.
- If you want to test the PR in dev environment, then you may be required to remove "updateDB" from weather repo Makefile.
- Test suite result:
` @============================================= 1189 passed, 13 skipped in 57.30 seconds =============================================
`
> FOGL-1340 - Any new south plugin should work without restarting server

- python/foglamp/services/core/api/backup_restore.py
- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
Execution :
```
foglamp@ubuntu:~$ cd /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/services/core/api;\
> python3 -m pytest -v test_backup_restore.py
==================================================== test session starts ====================================================
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
rootdir: /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/services/core/api, inifile:
collected 38 items
test_backup_restore.py::TestBackup::test_get_status[1-RUNNING] PASSED                                                 [  2%]
test_backup_restore.py::TestBackup::test_get_status[2-COMPLETED] PASSED …
```
> Fogl 1343: fix services/core/api/test_backup_restore.py

- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
**Tests suite result**
> == 1195 passed, 13 skipped in 69.24 seconds ==
Individual report result 
```
collected 38 items                                                                                                                                    
services/core/api/test_backup_restore.py::TestBackup::test_get_status[1-RUNNING] PASSED
services/core/api/test_backup_restore.py::TestBackup::test_get_status[2-COMPLETED] PASSED
services/core/api/test_backup_restore.py::TestBackup::test_get_status[3-CANCELED] PASSED
services/core/api/test_backup_restore.py::TestBackup::test_get_status[4-INTERRUPTED] PASSED
services/core/api/test_backup_restore.py::TestBackup::test_get_status[5-FAILED] PASSED
services/core/api/test_backup_restore.py::TestBackup::test_get_status[6-RESTORED] PASSED …
```
> FOGL-1344 skip annotation removed from test back up and restore

- python/foglamp/common/web/middleware.py
- python/foglamp/plugins/common/utils.py
- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/certificate_store.py
- python/foglamp/services/core/api/support.py
- python/foglamp/services/core/support.py
> python/foglamp/common/web
middleware.py
> python/foglamp/plugins/common
utils.py
> python/foglamp/services/core
support.py
> python/foglamp/services/core/api
audit.py
certificate_store.py
support.py
**WE NEED INFO for following, in any case:**
> python/foglamp/plugins/south/cc2650async
cc2650async.py
> python/foglamp/plugins/south/cc2650poll
cc2650poll.py
> python/foglamp/plugins/south/common
sensortag_cc2650.py
> python/foglamp/plugins/south/http_south
http_south.py
> python/foglamp/services/common
utils.py
> python/foglamp/services/core
server.py
> python/foglamp/services/core/service_registry
monitor.py
service_registry.py
> python/foglamp/services/core/scheduler
scheduler.py
> python/foglamp/services/core/api
common.py
update.py
**Not sure about these files:**
> …
> FOGL-1347 Remove logger "level=20" when making logger instance

- C/plugins/storage/common/sql_buffer.cpp
- C/services/storage/storage_api.cpp
Fixed small memory leak in purge and new[] delete mismatch.
@Singhal-Vaibhav can you please rerun your long term test against this branch
> FOGL-1355 Fix for memory leaks

- python/requirements-test.txt
pylint==1.9.1 | http://pylint.pycqa.org/en/latest/whatsnew/changelog.html#what-s-new-in-pylint-1-9
pytest==3.6.0 | https://docs.pytest.org/en/latest/changelog.html
pytest-mock==1.10.0 | https://pypi.org/project/pytest-mock/1.10.0/#history
_NOTE_:
aiopg, asyncpg, SQLAlchemy -- deps required for **integration** tests only and will be taken care in https://scaledb.atlassian.net/browse/FOGL-1300
psycopg2 dep removed from here, as this is a duplicate (already exist in requirements.txt)
**Tests O/P**
`=== 1149 passed, 13 skipped in 61.04 seconds ===`
Lint is okay
Allure-report is okay
Coverage is okay
> FOGL-1361 test dependencies updated as per latest and stable released versions

- C/common/include/expression.h
- C/common/include/storage_client.h
- C/common/storage_client.cpp
- tests/unit/C/common/test_expression.cpp
> FOGL-1330 Add expressions to update

- tests/unit/python/foglamp/tasks/purge/test_purge.py
Test Results:
`== 16 passed in 0.16 seconds ==`
Test Coverage:
```
Coverage for FogLAMP/python/foglamp/tasks/purge/purge.py : 100% 
77 statements   77 run 0 missing 0 excluded
```
> FOGL-1393: Fix unit test tasks/purge/test_purge.py

- tests/unit/python/foglamp/tasks/north/test_sending_process.py
ready for review/merge.
```
...
tasks/north/test_sending_process.py::TestSendingProcess::test_start_stream_not_valid PASSED
tasks/north/test_sending_process.py::TestSendingProcess::test_start_sp_disabled PASSED
tasks/north/test_sending_process.py::TestSendingProcess::test_start_not_north PASSED
tasks/north/test_sending_process.py::TestSendingProcess::test_start_good PASSED
----------- coverage: platform linux, python 3.5.2-final-0 -----------
Name                                                                              Stmts   Miss  Cover
-----------------------------------------------------------------------------------------------------
/home/foglamp/Development/FogLAMP/python/foglamp/tasks/north/__init__.py              0      0   100% …
```
> Fogl 1358: Adapt the unit tests for SP and north plugins in relation to Async functionalities

- python/foglamp/common/process.py
- tests/unit/python/foglamp/common/test_process.py
- tests/unit/python/foglamp/plugins/north/http_north/test_http_north.py
- tests/unit/python/foglamp/services/common/test_microservice.py
- tests/unit/python/foglamp/services/core/api/test_service.py
- tests/unit/python/foglamp/services/core/scheduler/test_scheduler.py
- tests/unit/python/foglamp/services/south/test_ingest.py
```
tests/unit/python/foglamp/plugins/north/ocs/test_ocs.py ......FF..FFF
tests/unit/python/foglamp/plugins/north/omf/test_omf.py .....F..FFFFFFFFFFFFFFFF.........F......
======================================= 23 failed, 1200 passed, 35 skipped, 11 warnings in 94.82 seconds ========================================
```
> Tests fixed. New tests added to scheduler tests to cover new functionalities added.

- docs/05_testing.rst
- docs/06_plugins/03_south_plugins.rst
- docs/07_admin/02_RESTadmin.rst
- python/foglamp/plugins/north/http_north/http_north.py
- python/foglamp/plugins/north/omf/omf.py
- python/foglamp/plugins/storage/common/lib.py
- python/foglamp/plugins/storage/postgres/backup_restore/lib.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/core/server.py
- python/foglamp/services/core/service_registry/monitor.py
- python/foglamp/services/south/ingest.py
- python/foglamp/tasks/north/sending_process.py
- python/foglamp/tasks/purge/purge.py
- scripts/plugins/storage/postgres/init.sql
- scripts/plugins/storage/sqlite/init.sql
- tests/unit/python/foglamp/services/south/test_ingest.py
https://scaledb.atlassian.net/browse/FOGL-1420
Most of the work done by Bill, I just verified the changes and fixed below items:
> FOGL-1420 Change category description text

- python/foglamp/services/south/ingest.py
Test result:
`============================================= 1220 passed, 35 skipped, 1 warnings in 95.84 seconds ==============================================
`
> FOGL-1441 - Remove/reduce wait on empty queues in ingest.py

- C/common/include/process.h
- C/common/include/query.h
- C/common/process.cpp
- C/common/query.cpp
- C/common/reading.cpp
- C/common/reading_set.cpp
- C/common/result_set.cpp
- C/common/storage_client.cpp
- C/services/storage/storage_api.cpp
- C/tasks/statistics_history/CMakeLists.txt
- C/tasks/statistics_history/include/stats_history.h
- C/tasks/statistics_history/main.cpp
- C/tasks/statistics_history/stats_history.cpp
- tests/unit/C/common/test_query.cpp
This is for a merge to the FOGL-1330 branch not develop.
- Implementation of Statistics History
- Addition to Storage Client to include areas previously missed
> FOGL-1418 C++ Implementation of Statistics History Process

- tests/unit/python/foglamp/services/core/api/test_browser_assets.py
> pytest -s -vv services/core/api/test_browser_assets.py
> ==== 42 passed in 1.28 seconds ===
> Coverage for /home/foglamp/Development/FogLAMP/python/foglamp/services/core/api/browser.py : 100% 
> 150 statements   150 run 0 missing 0 excluded
> Suite result
> == 1219 passed, 36 skipped, 1 warnings in 102.77 seconds ==
> FOGL-1448 assets browser unit tests fixes as per new changes from PR#806

- python/foglamp/plugins/north/ocs/ocs.py
- python/foglamp/plugins/north/omf/omf.py
tested in : 
- Ubuntu server : PI / OCS
- Raspberry : PI / OCS
> FOGL-1478: urllib3 removed.

- python/foglamp/plugins/storage/common/lib.py
- python/foglamp/plugins/storage/postgres/backup_restore/backup_postgres.py
- python/foglamp/plugins/storage/postgres/backup_restore/exceptions.py
- python/foglamp/plugins/storage/postgres/backup_restore/lib.py
- python/foglamp/plugins/storage/postgres/backup_restore/restore_postgres.py
- python/foglamp/plugins/storage/sqlite/backup_restore/restore_sqlite.py
- python/requirements.txt
tested in : 
* vbox/Ubuntu server - Development
* raspberry - Deploy
> Fogl 1475: remove the use/requirement of the psycopg2 library in the Python code

- python/foglamp/services/core/api/statistics.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
Code Coverage: **100%**
unit tests: **All passed**
**NOTE:** : 1 test failure is expected. See FOGL-1481
> FOGL-1485 REST end point added to get single stat history on the basis of key

- tests/unit/python/foglamp/tasks/north/test_sending_process.py
=================== 1137 passed, 33 skipped in 91.02 seconds ===================
Ignore the CI report! FOGL-1507
> removed http north integration check (part of FOGL-1481)

- C/plugins/storage/postgres/plugin.cpp
- C/plugins/storage/sqlite/connection.cpp
- C/plugins/storage/sqlite/plugin.cpp
- C/plugins/storage/sqlitememory/plugin.cpp
Tested by running period every second for more then 16 hours
> FOGL-1527 Fix issue with lost connections from purge

- C/common/include/config_category.h
- C/common/include/management_client.h
- C/common/include/process.h
- C/common/management_client.cpp
- C/tasks/north/sending_process/include/sending.h
- C/tasks/north/sending_process/sending.cpp
- C/tasks/north/sending_process/sending_process.cpp
- C/thirdparty/Simple-Web-Server/client_https.hpp
- scripts/foglamp
- scripts/plugins/storage/postgres/init.sql
- scripts/plugins/storage/sqlite/init.sql
- scripts/tasks/north_c
**Development completed.**
**testing**
foglamp kill tested in raspbian : 
```
Jul 10 09:16:26 raspberrypi FogLAMP Process[6727]: SendingProcess/sending - signal received :1:
Jul 10 09:16:26 raspberrypi FogLAMP Process[6727]: SendingProcess is stopping due to caught signal 1 (Hangup)
Jul 10 09:16:26 raspberrypi FogLAMP Process[6727]: SendingProcess is stopping, after 45 seconds.
Jul 10 09:16:26 raspberrypi FogLAMP Storage[11202] INFO: script.plugin.storage.sqlite: FogLAMP database is SQLite3. No stop/start actions available
Jul 10 09:16:26 raspberrypi FogLAMP [11202] INFO: script.foglamp: FogLAMP killed.
```
foglamp stop tested in raspbian : 
```
Jul 10 09:24:00 raspberrypi FogLAMP Process[8612]: SendingProcess/sending - signal received :15:
Jul 10 09:24:00 raspberrypi FogLAMP …
```
> Fogl 1503: Improved configuration handling for the sending process - C code

- python/foglamp/services/core/api/backup_restore.py
- python/foglamp/services/core/api/task.py
- python/foglamp/services/core/routes.py
- python/foglamp/tasks/north/sending_process.py
- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
- tests/unit/python/foglamp/services/core/api/test_task.py
Diff is only for below implementation:
https://scaledb.atlassian.net/browse/FOGL-1487
https://scaledb.atlassian.net/browse/FOGL-1494
> Fogl 1432 sync with develop

- python/foglamp/common/configuration_manager.py
- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
JSON field Display problem pending
> FOGL-1570 JSON config validation fixes

- python/foglamp/common/microservice_management_client/microservice_management_client.py
- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/common/microservice_management_client/test_microservice_management_client.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
Test result:
`=================================================== 1163 passed, 31 skipped in 85.30 seconds ====================================================
`
> FOGL-1531 - Bad REST payload

- python/foglamp/common/microservice_management_client/microservice_management_client.py
- python/foglamp/services/common/microservice.py
- python/foglamp/services/common/microservice_management/routes.py
- python/foglamp/services/core/server.py
- tests/unit/python/foglamp/services/common/test_microservice.py
Test result:
`================================================= 1246 passed, 31 skipped in 90.63 seconds =================================================
`
> FOGL-1600 - Add Security as a child to General category (remove TODO from microservice.py)

- python/foglamp/common/configuration_manager.py
- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
curl -sX GET 'http://localhost:8081/foglamp/category?root=true&children=true'
curl -sX GET 'http://localhost:8081/foglamp/category?root=false&children=true'
curl -sX GET 'http://localhost:8081/foglamp/category?root=true
curl -sX GET 'http://localhost:8081/foglamp/category
> FOGL-1575 nested array of children for a cateogry only if root value is there

- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/api/task.py
- tests/unit/python/foglamp/services/core/api/test_service.py
- tests/unit/python/foglamp/services/core/api/test_task.py
Test result:
`=================================================== 1286 passed, 36 skipped in 95.44 seconds ====================================================
`
> FOGL-1640 - server side enhancements to add group (aka parent) info to schedules list

- python/foglamp/services/core/api/task.py
- tests/unit/python/foglamp/services/core/api/test_task.py
Also, see https://scaledb.atlassian.net/browse/FOGL-1754
> Fogl 1740 - add_task service for C type plugin

- C/tasks/north/sending_process/sending.cpp
- VERSION
- python/foglamp/plugins/north/ocs/ocs.py
- python/foglamp/plugins/north/pi_server/pi_server.py
- python/foglamp/tasks/north/sending_process.py
- scripts/plugins/storage/postgres/downgrade/11.sql
- scripts/plugins/storage/postgres/init.sql
- scripts/plugins/storage/postgres/upgrade/12.sql
- scripts/plugins/storage/sqlite/downgrade/11.sql
- scripts/plugins/storage/sqlite/init.sql
- scripts/plugins/storage/sqlite/upgrade/12.sql
- tests/unit/python/foglamp/tasks/north/test_sending_process.py
> Fogl 1641 : The destinations table is obsolete and will be removed

- tests/unit/python/foglamp/services/core/api/test_common_ping.py
Test result:
`=================================================== 1289 passed, 39 skipped in 97.96 seconds ====================================================
`
> FOGL-1601 - Refactor the test for ping method of Admin API

- C/thirdparty/Simple-Web-Server/CMakeLists.txt
- C/thirdparty/Simple-Web-Server/LICENSE
- C/thirdparty/Simple-Web-Server/README.md
- C/thirdparty/Simple-Web-Server/client_http.hpp
- C/thirdparty/Simple-Web-Server/client_https.hpp
- C/thirdparty/Simple-Web-Server/crypto.hpp
- C/thirdparty/Simple-Web-Server/http_examples.cpp
- C/thirdparty/Simple-Web-Server/https_examples.cpp
- C/thirdparty/Simple-Web-Server/server_http.hpp
- C/thirdparty/Simple-Web-Server/server_https.hpp
- C/thirdparty/Simple-Web-Server/status_code.hpp
- C/thirdparty/Simple-Web-Server/tests/CMakeLists.txt
- C/thirdparty/Simple-Web-Server/tests/io_test.cpp
- C/thirdparty/Simple-Web-Server/tests/parse_test.cpp
- C/thirdparty/Simple-Web-Server/utility.hpp
Tested fulll lifecycle including sending to connector relay
> FOGL-1799 Update version of Simple Web Server

- C/plugins/storage/postgres/connection.cpp
- C/plugins/storage/sqlite/connection.cpp
$ curl -X GET http://localhost:8081/foglamp/category/"foo'bar"
404: No such Category found for foo'bar
$ curl -X GET http://localhost:8081/foglamp/category/"foo;bar"
404: No such Category found for foo;bar
$ curl -X POST http://localhost:8081/foglamp/scheduled/task -d@x.json
{"id": "c2211937-03a3-447e-b7b2-8c787e1a28af", "name": "North'Readings'to'PI"}
$
> FOGL-1552 Fix escaping in where clause

- python/requirements.txt
Added details in FOGL-1823
/cc @MarkRiddoch
> [FOGL-1823] Test and use latest aiohttp version especially around timeout / connection wait time etc.

- python/foglamp/plugins/north/ocs/ocs.py
- python/foglamp/plugins/north/pi_server/pi_server.py
- python/foglamp/tasks/north/sending_process.py
note :  'source' configuration moved to the plugin, handling updated.
> FOGL-1831: Send FogLAMP statistics to PI

- python/foglamp/plugins/north/ocs/ocs.py
- python/foglamp/plugins/north/pi_server/pi_server.py
- python/foglamp/tasks/north/sending_process.py
> FOGL-1830: working stage.

- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/tasks/north/sending_process.py
Test result:
`============================================== 1314 passed, 39 skipped in 112.42 seconds ==============================================
`
> FOGL-1847 - South services do not stop after disabling the schedule

- python/foglamp/plugins/north/pi_server/pi_server.py
- python/foglamp/tasks/north/sending_process.py
- tests/unit/python/foglamp/plugins/north/pi_server/test_pi_server.py
Refer: JIRA  [FOGL-1594] Point#8
> Pi omf compression [FOGL-1594] Point#8

- C/common/include/management_client.h
- C/common/management_client.cpp
- C/common/process.cpp
- C/services/south/south.cpp
Created a random south service instance and north pi_server task with their names having a space in the middle. Worked fine under various scenarios.
Oct  3 13:22:10 foglamp-VirtualBox FogLAMP Process[15943]: getCategory: URL='/foglamp/servi1ce/category/pi%20server1'
Oct  3 13:22:10 foglamp-VirtualBox FogLAMP Process[15943]: response='404: Not Found'
Oct  3 13:22:10 foglamp-VirtualBox FogLAMP Process[15943]: HTTP error while fetching configuration category for pi server: 404: Not Found
Oct  3 13:22:40 foglamp-VirtualBox FogLAMP Process[15979]: getCategory: URL='/foglamp/servi1ce/category/pi%20server1'
Oct  3 13:22:40 foglamp-VirtualBox FogLAMP Process[15979]: response='404: Not Found'
Oct  3 13:22:40 foglamp-VirtualBox FogLAMP Process[15979]: HTTP error while fetching configuration …
> FOGL-1722: C++ Management Client cleanup

- python/foglamp/services/south/ingest.py
- tests/unit/python/foglamp/services/south/test_ingest.py
Test result:
`================================================================================== 1390 passed, 39 skipped in 107.85 seconds ==================================================================================
`
> FOGL-1872 - South service to add advanced configuration as child category

- python/foglamp/services/south/server.py
Now pollInterval is working more accurately. Below is a sample output from systeminfo plugin, run in poll mode. user_ts is now recorded quite accurately.
```
id	asset_code	read_key	                        reading	                                        user_ts	                                ts
1	system/hostName	8c8dd4dc-1335-4d35-be2a-4a4fcb3b972e	"{""hostName"":""asinha-ThinkPad-E450""}"	2018-10-03 18:00:30.106378+05:30	2018-10-03 18:00:34.593
20	system/hostName	aeda2c59-9115-4e75-8dc4-4a6c658752d8	"{""hostName"":""asinha-ThinkPad-E450""}"	2018-10-03 18:00:31.524034+05:30	2018-10-03 18:00:34.593
39	system/hostName	69516940-c7b9-4faa-9041-431613ad5a9a	"{""hostName"":""asinha-ThinkPad-E450""}"	2018-10-03 18:00:32.527335+05:30	2018-10-03 18:00:34.593
58	system/hostName …
```
> FOGL-1909 - Adjust sleep values based on execution time for python south service

- python/foglamp/services/south/server.py
> Revert "FOGL-1909 - Adjust sleep values based on execution time for python south service"

- C/common/management_client.cpp
- C/plugins/common/include/omf.h
- C/plugins/common/omf.cpp
- C/services/south/include/defaults.h
- C/services/south/include/south_service.h
- C/services/south/ingest.cpp
- C/services/south/south.cpp
- C/tasks/north/sending_process/sending_process.cpp
Let me know if I should retain the omf.h and omf.cpp changes or not.
> FOGL-1801: FogLAMP Benchmarking activities

- python/foglamp/plugins/storage/common/lib.py
- python/foglamp/services/common/microservice.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/core/server.py
- python/foglamp/services/core/service_registry/monitor.py
- python/foglamp/tasks/purge/purge.py
> FOGL-1956 Display name fixes for category and its config items

- python/requirements-test.txt
> upgrading requests lib version, moderate severity security vulnerability detected in requests <= 2.19.1

- C/plugins/storage/sqlite/connection.cpp
Perform the merge process in blocks, with a delay between each block, in order to allow other threads to get access to the SQLite database between blocks.
> FOGL-1986 Perform purge in blocks to allow access from other threads

- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/api/task.py
- python/foglamp/services/core/routes.py
Quick test output:
curl -X DELETE http://localhost:8081/foglamp/scheduled/task/http%20north
{"result": "North instance http north deleted successfully."}
> [FOGL-1928] delete north instance task api support

- C/common/config_category.cpp
- C/common/include/config_category.h
- C/services/south/include/south_service.h
- C/services/south/south.cpp
- CMakeLists.txt
- tests/unit/C/common/test_config_category.cpp
- tests/unit/C/common/test_default_config_category.cpp
working progress, code preview
Json sample used for test of the Random plugin : 
```
#define CONFIG	"{" \
"\"plugin\" : {"\
"\"description\" : \"" PLUGIN_NAME " C south plugin\", " \
"\"type\" : \"string\", "\
"\"default\" : \"" PLUGIN_NAME "\" "\
"}, "\
"\"asset\" : {"\
"\"description\" : \"Asset name\", " \
"\"type\" : \"string\", "\
"\"default\" : \"Random\" "\
"}, "\
"\"V1_NewCat\" : {"\
"\"description\" : \"XXX_1 options\", "\
"\"type\" : \"category\", "\
"\"default\" : {"\
"\"bias\" : {"\
"\"description\" : \"Bias offset\", "\
"\"type\" : \"float\", "\
"\"default\" : \"0\" "\
"}, "\
"\"phase\" : {"\
"\"description\" : \"Phase angle (degrees) \", "\
"\"type\" : \"integer\", "\
"\"default\" : \"0\", "\
"\"order\" : \"2\" "\
"} "\
"} "\
"}, "\
"\"V2_NewCat\" : {"\
"\"description\" : …
```
> Fogl 1918: Add support in the south C++ service for sub-categories

- C/plugins/common/omf.cpp
- C/plugins/common/simple_https.cpp
*Cases*
**Error - network down** : 
```
Nov  6 10:29:04 ihsdev FogLAMP Process[26746]: Sending JSON dataType message 'Type' - generic error: |Failed to send data: No route to host| - HostPort |WIN-4M7ODKB0RH2:5460| - path |/ingress/messages| - OMF message |[{ "type": "object", "properties": { "Company": {"type": "string"}, "Location": {"type": "string"}, "Name": { "type": "string", "isindex": true } }, "classification": "static", "id": "1_sinusoid_typename_sensor" }, { "type": "object", "properties": {"sinusoid": {"type": "number", "format": "float64"}, "Time": {"type": "string", "isindex": true, "format": "date-time"}}, "classification": "dynamic", "id": "1_sinusoid_typename_measurement" }]|
```
to reproduce
```
#
VBoxManage controlvm DianomicPIServer   setlinkstate1 off;\
VBoxManage …
```
> FOGL-1811:  C++ OMF plugin doesn't log why sends fail, only the http response code is logged

- C/common/reading_set.cpp
sample cases handled
```
INSERT INTO "readings" VALUES(NULL,'case_005_002','1a6cd43a-d316-43d9-a0d4-dd1e57005002','xxx', '2018-08-02 16:33:25.082760+01:00','2018-08-02 16:33:28.092');
INSERT INTO "readings" VALUES(NULL,'case_005_002','1a6cd43a-d316-43d9-a0d4-dd1e57005201','xx1', '2018-08-02 16:33:26.082760+01:00','2018-08-02 16:33:28.092');
INSERT INTO "readings" VALUES(NULL,'case_005_002','1a6cd43a-d316-43d9-a0d4-dd1e57005202','xx2', '2018-08-02 16:33:27.082760+01:00','2018-08-02 16:33:28.092');
```
> FOGL-2040: SP/C++ : it crashes in case of a bad formatted readings - stage 1

- C/common/reading_set.cpp
Cases : 
```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
-- String
INSERT INTO "readings" VALUES(NULL,'case_2038_002','1a6cd43a-d316-43d9-a0d4-000000000002','xxx' ,'2018-08-02 16:33:24.081574+01:00','2018-08-02 16:33:28.092');
-- Int
INSERT INTO "readings" VALUES(NULL,'case_2038_003','1a6cd43a-d316-43d9-a0d4-000000000003','-1' ,'2018-08-02 16:33:24.081574+01:00','2018-08-02 16:33:28.092');
INSERT INTO "readings" VALUES(NULL,'case_2038_004','1a6cd43a-d316-43d9-a0d4-000000000004','0' ,'2018-08-02 16:33:24.081574+01:00','2018-08-02 16:33:28.092');
INSERT INTO "readings" VALUES(NULL,'case_2038_005','1a6cd43a-d316-43d9-a0d4-000000000005','-1' ,'2018-08-02 16:33:24.081574+01:00','2018-08-02 16:33:28.092');
-- Float
INSERT INTO "readings" …
```
> FOGL-2038: SP/C++ handling reading bad cases

- python/foglamp/services/core/api/filters.py
- tests/unit/python/foglamp/services/core/api/test_filters.py
**Code Coverage: 79%**
Only delete filter pipeline is incomplete and have skip annotation. Most of the Pending coverage only for internal defs which is not required.
> FOGL-2081 filter api tests added and service reference removal from its api file

- python/foglamp/services/core/__main__.py
- python/foglamp/services/core/api/common.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/core/server.py
- scripts/foglamp
- tests/unit/python/foglamp/services/core/api/test_common_ping.py
> FogL 2182 - safe mode startup option

- python/foglamp/services/core/api/notification.py
- tests/unit/python/foglamp/services/core/api/test_notification.py
This completely revises POST and PUT endpoints for admin api for notifications. The major changes are as follows:
a) Now POST notification endpoint does not create any configuration category at all. It sends POST requests to notification server to create categories (from template) and associated child categories for notification, rule and delivery. After that it simply updates the newly created categories with the values supplied in the POST payload. 
b) PUT notification endpoint can now modify the notification and associated categories for rule and delivery without supplying the full configuration for rule/channel. Partial/nil configuration can be supplied for new rule/channel values and if no configuration is supplied for new rule/channel then it is picked from default.
This PR may be …
> FOGL-2210: Changes in notification API post modifications in C++ notification server

- C/tasks/north/sending_process/include/sending.h
- C/tasks/north/sending_process/sending.cpp
- python/foglamp/services/core/server.py
**New algorithm implemented**
the 2 sending processes in C++ and in python related to the reading are reset 
not the statistics one
> FOGL-1617: Improve the handling of the streams table for in memory table that are source of data

- tests/system/python/README.rst
- tests/system/python/conftest.py
- tests/system/python/pytest.ini
- tests/system/python/test_e2e_coap_PI.py
- tests/system/python/test_e2e_csv_PI.py
- tests/system/python/test_smoke.py
> FOGL-2322 system test for ingestion of data in a Kafka system

- C/plugins/storage/sqlite/connection.cpp
from the service
Merge to develop
> FOGL-2451 Make no data to purge a log message

- python/foglamp/plugins/common/shim/shim.py
This PR takes care of JSON type configuration items during plugin_reconfigure() for Python Poll plugins.
For Python Async plugins, we need to check and convert JSON type config items to json objects in plugin_start() or any method called by plugin_start() as appropriate. For example, please refer to playback plugin. Here config['readingCols] is a JSON type item and it is being converted to json object at line#320:
`
self.reading_cols = rc if isinstance(rc, dict) else json.loads(rc)
`
This helps plugin_reconfigure() to run without any error.
> Fogl 2511 patch -  Fix JSON type configuration items for plugin_reconfigure() in shim layer

- C/common/logger.cpp
- C/plugins/storage/sqlite/connection.cpp
- C/plugins/storage/sqlite/include/profile.h
- C/services/south/south.cpp
- C/services/storage/storage_api.cpp
- scripts/plugins/storage/sqlite.sh
Further changes related to performance improvement with SQLite DB picked from FOGL-2489-1 branch. Some debug logs have been retained to help debug in case of long duration test. These would be removed when merging back into develop.
> FOGL-2489: Changes related to performance improvement while using SQLite

- python/foglamp/services/core/server.py
it was taking 3+ minutes to execute on a large DB on foglamp start
> #no-ticket readings table empty check query optmization;

- tests/system/python/conftest.py
- tests/system/python/e2e/test_e2e_csv_multi_filter_pi.py
Playback plugin with multiple filters in pipeline - delta filter, RMS filter, rate filter, scale filter, asset filter and meta filter and send data to PI
> FOGL-2181: Add filters to system test

- tests/system/python/api/test_configuration.py
- tests/system/python/e2e/test_e2e_coap_OCS.py
- tests/system/python/e2e/test_e2e_expr_pi.py
TODO:
~|-- asset_tracker.py~
~|-- update.py~
~`-- utils.py~
> FOGL-2396   System integration test for API 

- C/plugins/storage/postgres/connection.cpp
- C/plugins/storage/postgres/include/connection.h
- C/plugins/storage/sqlite/connection.cpp
- C/plugins/storage/sqlite/include/connection.h
- C/plugins/storage/sqlitememory/connection.cpp
- C/plugins/storage/sqlitememory/include/connection.h
*Tested*
* Raspibian
* u18
* send FB data
> FOGL-2636:  fix a possible memory leak in the usage of the 'escape' function in the postgress and SQLITE

- C/plugins/storage/postgres/connection.cpp
- C/plugins/storage/postgres/include/connection.h
PG reserved words like 'user' should be double quotes "user"
> Fogl 2500: Postgres DB: Unable to add multiple filters in pipeline

- tests/unit/C/services/storage/postgres/tests.cpp
Select the proper storage.json file for the tests.
> FOGL-2650: Fix postgres unit tests for the execution on the remote testing system

- C/plugins/storage/postgres/connection.cpp
- C/plugins/storage/postgres/include/connection.h
- C/plugins/storage/postgres/plugin.cpp
- C/plugins/storage/sqlite/common/connection.cpp
- C/plugins/storage/sqlite/plugin.cpp
- C/services/storage/include/storage_api.h
- C/services/storage/include/storage_plugin.h
- C/services/storage/storage_api.cpp
- C/services/storage/storage_plugin.cpp
> Revert "FOGL-2698: GET endpoint for snapshots"

- tests/system/python/e2e/test_e2e_foglamp_pair.py
bypass user confirmation to add to known host
> FOGL-2661: Run pair test on jenkins

- README.rst
- docs/building_foglamp/building_foglamp.rst
- python/foglamp/services/common/service_announcer.py
- python/foglamp/services/core/server.py
- requirements.sh
> FOGL-2641 (patch) name and desc fixes for service and readme cleanup for dep

- tests/system/python/conftest.py
- tests/system/python/e2e/test_e2e_modbus_c_pi.py
To execute the test, run a modbus simulator at port 502, e.g:
```
sudo docker create --name modbus-device -p <HOST_IP>:502:502 edgepro/c-modbus-slave
sudo docker start modbus-device
```
Then execute the test:
```
pytest test_e2e_modbus_c_pi.py --modbus-host=<MODBUS_SIMULATOR_HOST> --modbus-port=502 --pi-db=<PI_DB> --pi-host=<PI_HOST_IP> --pi-admin=<PI_ADMIN> --pi-passwd=<PI_PWD> --pi-token="<PI_TOKEN>"
==== 1 passed in 154.20 seconds ===
```
> FOGL-2761: System Test using modbus south plugin

- python/foglamp/services/core/api/plugins/install.py
- tests/unit/python/foglamp/services/core/api/plugins/test_install.py
```
curl -X POST http://localhost:8081/foglamp/plugins -d '{"url":"http://archives.dianomic.com/1.6.0/rhel76/foglamp-south-sinusoid-1.6.0-1.x86_64.rpm", "format":"rpm", "compressed":false, "type": "south", "checksum": "04bd924371488d981d9a60bcb093bedc"}'
{"message": "foglamp-south-sinusoid-1.6.0-1.x86_64.rpm is successfully downloaded and installed"}
```
**Package is installed on machine**
```
$ sudo yum search foglamp
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
============================================================ N/S matched: foglamp =============================================================
foglamp.x86_64 : FogLAMP, the open source platform for the Internet of Things
foglamp-south-sinusoid.x86_64 : FogLAMP foglamp-south-sinusoid plugin, the open source platform …
```
> FOGL-2868 rpm packages support added in POST plugin API

- C/plugins/storage/postgres/CMakeLists.txt
- C/plugins/storage/postgres/CheckRhPg.cmake
- docs/REDHAT.rst
- requirements.sh
- scripts/foglamp
- scripts/services/storage
- tests/unit/C/cmake_pg/CMakeLists.txt
- tests/unit/C/cmake_pg/CheckRhPg.cmake
- tests/unit/C/plugins/storage/postgres/CMakeLists.txt
- tests/unit/C/plugins/storage/postgres/CheckRhPg.cmake
done : 
* removed the hardcoded paths like - opt/rh/rh-postgresql96/root/usr/include
Tested : 
- AWS - RH
- AWS - CentOS
> Fogl 2801 - PostgreSQL on RHEL/CentOS

- tests/system/python/e2e/test_e2e_modbus_c_pi.py
> FOGL-2876: Add a modbus simulator in CI network to be accessed by modbus system test

- python/foglamp/common/configuration_manager.py
@MarkRiddoch Would you mind to test this?
> FOGL-2925 merge configuration handling for optional attributes

- tests/system/python/api/test_authentication.py
Tests positive scenarios with authentication set to mandatory.
Test Results:
===== 18 passed in 38.37 seconds =====
> FOGL-2612: Add system API tests for auth

- tests/unit/C/common/test_string_utils.cpp
- tests/unit/C/plugins/common/test_omf_translation_piwebapi.cpp
> Fogl 2949 :  unit tests related to PI Web API as end-point

- C/plugins/common/include/simple_http.h
- C/plugins/common/include/simple_https.h
- C/plugins/common/simple_http.cpp
- C/plugins/common/simple_https.cpp
- C/plugins/north/PI_Server_V2/plugin.cpp
**Working stage** 
Log bad case :  
```
WARNING: PI-Server end-point discovery encountered the error :HTTP code |401| HTTP error |{"Message":"Authorization has been denied for this request."}|:
```
good case : 
```
North_Readings_to_PI[2983]:, DEBUG: PI Web API end-point - basic authentication
North_Readings_to_PI[2983]:, DEBUG: PI-Server end point auto discovery selected
North_Readings_to_PI[2983]:, DEBUG: PI Web API end-point basic authorization granted
```
Data + stat - loaded using Basic : 
```
curl -X PUT http://localhost:8081/foglamp/category/North_statistics_to_PI/AFHierarchy1Level              -d '{ "value" : "foglamp_stat_piwebapi" }'
curl -X PUT http://localhost:8081/foglamp/category/North_statistics_to_PI/PIWebAPIAuthenticationMethod   -d '{ "value" : "basic" }'
curl -X PUT …
```
> Fogl 2918; Pi_Server plugin : handle authentication - basic using username/pwd

- python/requirements-test.txt
- tests/system/python/conftest.py
- tests/system/python/e2e/test_e2e_modbus_c_rtu_pi.py
test execution:
/FogLAMP/tests/system/python/e2e$ pytest -s -vv test_e2e_modbus_c_rtu_pi.py --modbus-serial-port=<VALUE> --modbus-baudrate <other_pi_config>
Result:
===== 1 passed in 35.85 seconds ===
> FOGL-2980: Automate testing of Modbus RTU

- python/foglamp/services/core/api/statistics.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
As asked in JIRA to provide stats history GET either with single or list of keys
```
curl -X GET http://localhost:8081/foglamp/statistics/history?key=READINGS,PURGED,UNSENT&minutes=60
curl -X GET http://localhost:8081/foglamp/statistics/history?key=READINGS
```
> FOGL-2370 multiple keys filter added in stats history endpoint

- tests/system/python/api/test_service.py
> wait time fix for API system test on restart -  RPi specific

- tests/system/python/api/test_audit.py
- tests/system/python/api/test_configuration.py
> FOGL-3128 System API test fixes

- README.rst
- docs/91_version_history.rst
> changes in README & rearranged version history

- requirements.sh
- scripts/tasks/statistics
* FOGL-3164: limit cpu usage by statistics  python process
* FOGL-3164: cpu limit to 40
* FOGL-3164: added OS check
> FOGL-3164 : statistics collector is very CPU intensive on RPi Zero 

- C/common/filter_pipeline.cpp
- C/common/include/filter_pipeline.h
- C/services/south/ingest.cpp
FOGL-3170: Add pipeline ready check
> FOGL-3170 [1.7.0 rc]

- C/plugins/north/PI_Server_V2/plugin.cpp
- scripts/foglamp
- scripts/tasks/statistics
* FOGL-3189:  cpu limit to 40
* FOGL-3189: simplified handlings
> FOGL-3189: Minor improvements 

- C/common/filter_pipeline.cpp
- C/common/include/filter_pipeline.h
- C/services/south/ingest.cpp
FOGL-3170: Add pipeline ready check
> FOGL-3170: Add pipeline ready check

- python/foglamp/services/core/server.py
> FOGL-3220 suppress SSLV3_ALERT_CERTIFICATE_UNKNOWN handshaking errors [1.7.0 RC]

- python/foglamp/services/core/server.py
(observed with chrome browser client) for python > 3.7 and < 3.7.4
> FOGL-3220 suppress SSLV3_ALERT_CERTIFICATE_UNKNOWN handshaking errors for  python > 3.7 and < 3.7.4

- python/foglamp/common/configuration_manager.py
`Squashed all commits` as its candidate of 1.7.0RC
> FOGL-3243 Ensure script type config item file content handling with CacheManager

- C/services/south/ingest.cpp
> FOGL-3251: fix for filter setup at service creation time (1.7.0 RC)

- tests/system/lab/test
- tests/system/lab/test.config
custom jobs/job/foglamp_lab_rpi0_ephat/18/
> FOGL-3037 (lab test) VERIFY_EGRESS_TO_PI option added

- python/foglamp/common/configuration_manager.py
Some fixes at plugin level https://github.com/foglamp/foglamp-filter-python35/pull/44
> FOGL-3179 upload script file attribute fixes when configuration run call back (1.7.0RC)

- python/foglamp/services/core/api/plugins/common.py
- python/foglamp/services/core/api/plugins/install.py
- python/foglamp/services/core/api/plugins/update.py
- scripts/extras/foglamp.sudoers
- scripts/extras/foglamp.sudoers_rh
- scripts/extras/update_task.apt
PR #1681
* FOGL-3158 Update command in sudoers fiel to match what is currently in
use
* Update foglamp.sudoers
* Update foglamp.sudoers_rh
* FOGL-3158 Always use -y flag with apt update
* yum check-update & upgrade commands added in package API endpoints
* apt used instead of apt-get for update_task.apt file
* FOGL-3256
> FOGL-3158 Update command in sudoers file to match what is currently in (1.7.0 RC)

- tests/system/lab/scripts/trendc.py
- tests/system/lab/test
custom jobs/job/foglamp_lab_rpi0_ephat/22/console `1.7.0RC`
vs
custom jobs/job/foglamp_lab_rpi0_ephat/21/console `nightly`
>ignore jq (23) Failed writing body - in Jenkins console for RPi0
> FOGL-3037 (lab test) added FOGL-3179 test case; and delete service with filter

- tests/system/python/api/test_audit.py
FOGL-3184: Addition of NTFCL #1695
>  FOGL-3184 API test fixed for added log code i.e. NTFCL
