foglamp/FogLAMP

- src/sql/foglamp.sql
- src/sql/foglamp_ddl.sql
- src/sql/foglamp_init_data.sql
@Terris-ScaleDB - Have a look at the changes in foglamp.readings, in particular line #456 with the uuid column, the default and the dup idx.
> Added readings.read_key

- src/python/build.sh
2. If venv/fogenv/bin/activate exists, don't run virtualenv or the other code is needed for virtualenv 5. If virtualenv is already active, don't exit as it currently does. Instead, use it.
> fogl-70 #2 and #5

- src/python/.pylintrc
- src/python/Makefile
- src/python/build.sh
- src/python/requirements.txt
- src/python/requirements_dev.txt
- src/python/requirements_doc.txt
- src/python/requirements_test.txt
- src/python/tox.ini
[FOGL-81](https://scaledb.atlassian.net/browse/FOGL-81)
Fixed items:
1) requirements - basic python dependencies
2) requirements_doc - only docs dependencies
3) requirements_test - only test dependencies
4) requirements_dev - python dependencies + test dependencies + docs dependencies
5) Now we should run our _doc and python_ tests by calling **make**
6) pip packages with their versions as standard process.
> FOGL-81 - pip requirements are now separated with their versions and tests call via make

- src/python/requirements_test.txt
- src/python/tests/device_api/coap/test_sensor_values.py
Benefits of using pytest-mock over unittest mock:
1. No unnecessary use of decorators
2. No passing of arguments in the test method and hence reducing the complexity of remembering the order of parameters passed wrt mock definitions.
3. Return value can be specified in mock itself.
For further reading please refer: https://github.com/pytest-dev/pytest-mock#why-bother-with-a-plugin
> Modified unit test for sensor values to use pytest-mock

- docs/build-tools.rst
- src/python/Makefile
[FOGL-256](https://scaledb.atlassian.net/browse/FOGL-256) - "make cov-report" is not working on Ubuntu
Fixed items:
1) `cov-report` now has OS check
2) Note added for allure command line installation in `build-tools.rst` updated
> FOGL-256 - "make cov-report" is not working on Ubuntu

- src/python/foglamp/core/api.py
- src/python/foglamp/core/routes.py
[FOGL-219](https://scaledb.atlassian.net/browse/FOGL-219) - Complimentary PR
Problem:
For setting configuration item in Rest API; We did a mistake on PUT! the value is in the payload, not a parameter in the URL
**To test this PR, please proceed as follows:**
1) Run query
```
INSERT INTO foglamp.configuration ( key, description, VALUE ) 
VALUES ( 'PURGE', 'Purge data process', '{"age": {"description": "Age of data to be retained, all data that is older than this value will be removed, unless retained. (in Hours)", "type": "integer", "default": "72"}}');
```
2) CURL request:
> curl -H "Content-Type: application/json" -X PUT -d '{"value":24}' http://localhost:8082/foglamp/category/PURGE/age
> 
> curl -X DELETE http://localhost:8082/foglamp/category/PURGE/age
> 
> curl -X GET …
> value is in payload not in URL parameter for set configuration item

- .gitignore
- benchmarks/.gitignore
- benchmarks/fogbench/__main__.py
**Output is not printed to console if arg (-o) is not provided, if provided, its printed to the given output file**
Example usage:
`FogLAMP/benchmarks $ python -m fogbench -t fogbench/templates/fogbench_sensor_coap.template.json -o fogbench.out`
- write stats to file fogbench/out/fogbench.out 
`FogLAMP/benchmarks $ python -m fogbench -t fogbench/templates/fogbench_sensor_coap.template.json`
- displays the stats on console
> Fogbench stats out

- src/python/foglamp/data_purge/purge.py
Since the code is single threaded non-async, it could work with a pool size of 1. However, to make things a little more safe, I have set the pool_size to 5.
> FOGL-430: Change connection pool size and close connection after execution in purge process

- src/python/tests/test_configuration_manager.py
The following are unit-tests for the configuration_manager. I'd greatly appreciate it if whomever looks at the code, can thoroughly double check stuff related to register_interest since it was the one method I wasn't 100% sure on.
> FOGL-491: Unit-Test for configuration_manager (Priority 1)

- src/python/foglamp/configuration_manager.py
- src/python/tests/test_configuration_manager.py
[FOGL-585](https://scaledb.atlassian.net/browse/FOGL-585) - Invalid Error when setting invalid category_name in create_category
* category name and description accepts only as string
* unit tests added for ^^ handling
* PEP8 warning fixes and other refactoring for configuration unit tests
**tests O/p**
tests/test_configuration_manager.py ................XXXXX...
==================================================== 19 passed, 5 xpassed in 1.48 seconds =====================================================
> fogl-585 : type error handling for category name and description with their unit tests

- src/python/foglamp/device/coap_device.py
- src/python/foglamp/device/server.py
- src/sql/foglamp_init_data.sql
1. change foglamp_init_data.sql - COAP configuration, task name for device is COAP also
2. change device server code to retrieve plugin to load (from configuration) based on command line argument passed in
> Fogl 650 startup and configuration of device server fix

- src/python/foglamp/data_purge/__main__.py
- src/python/foglamp/data_purge/purge.py
- src/python/tests/data_purge/test_data_purge.py
```
(FOGL-626-fix)$ pytest test_data_purge.py 
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.1.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/foglamp/foglamp/FogLAMP/src/python, inifile:
plugins: cov-2.5.1, asyncio-0.6.0, mock-1.6.0, allure-adaptor-1.7.7
collected 9 items 
test_data_purge.py .........
```
=========================== 9 passed in 2.00 seconds ===========================
> [FOGL-626] improved purge task, allow scalablity fixes

- src/C/foglamp/storage/plugins/postgres/connection.cpp
Age was being interpreted as seconds and not hours.
> FOGL-666 Fixed age issue with purge, was using seconds rather than hours

- Makefile
Note that it is expected that "make install" shouldn't be run as a non-root user (and will be documented as such).
> FOGL-751 fix pip to not use --system flag

- tests/unit-tests/python/foglamp_test/common/storage/test_payload_builder.py
- tests/unit-tests/python/foglamp_test/common/storage/test_storage_api.py
- tests/unit-tests/python/foglamp_test/common/test_configuration_manager.py
- tests/unit-tests/python/foglamp_test/tasks/purge/test_purge.py
[FOGL-762](https://scaledb.atlassian.net/browse/FOGL-762)
1) tests/unit-tests/python/foglamp_test/common/storage/test_payload_builder.py 
collected 60 items == 59 passed, 1 skipped
2) tests/unit-tests/python/foglamp_test/common/storage/test_storage_api.py
collected 30 items == 26 passed, 4 skipped
3) tests/unit-tests/python/foglamp_test/common/test_configuration_manager.py
collected 25 items == 20 passed, 1 skipped, 2 xfailed, 2 xpassed
4) Purge tests are failing due to inconsistency of log entries (i.e level/severity) [FOGL-695](https://scaledb.atlassian.net/browse/FOGL-695)
> import fixes in tests directory

- tests/unit-tests/python/foglamp_test/services/common/microservice_management/service_registry/test_instance.py
- tests/unit-tests/python/foglamp_test/services/common/microservice_management/service_registry/test_services_registry_api.py
[FOGL-761](https://scaledb.atlassian.net/browse/FOGL-761) - 
These were failing due to invalid service type: `Device vs Southbound`
**Tests O/P:**
**collected 24 items** 
> tests/unit-tests/python/foglamp_test/services/common/microservice_management/service_registry/test_instance.py ..........
tests/unit-tests/python/foglamp_test/services/common/microservice_management/service_registry/test_services_registry_api.py ..............
**========24 passed in 0.56 seconds =====**
> FOGL-761 service_registry test fixes; device type is Southbound

- tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py
[FOGL-576](https://scaledb.atlassian.net/browse/FOGL-576) -  REST API tests added for audit log
**Test O/P**
```
pytest -s -v test_audit.py 
======= test session starts =======
collected 16 items 
test_audit.py::TestAudit::test_get_severity PASSED
test_audit.py::TestAudit::test_get_log_codes PASSED
test_audit.py::TestAudit::test_get_audit PASSED
test_audit.py::TestAudit::test_get_audit_with_offset PASSED
test_audit.py::TestAudit::test_get_audit_by_code PASSED
test_audit.py::TestAudit::test_get_audit_by_code_and_level PASSED
test_audit.py::TestAudit::test_get_audit_by_code_and_level_with_limit PASSED
test_audit.py::TestAudit::test_get_audit_by_code_and_level_with_limit_and_offset PASSED
test_audit.py::TestAudit::test_get_audit_with_invalid_severity PASSED …
```
>  FOGL-576 REST API tests added for audit log

- python/foglamp/common/storage_client/payload_builder.py
- tests/unit-tests/python/foglamp_test/common/storage/data/payload_aggregate_where.json
- tests/unit-tests/python/foglamp_test/common/storage/data/payload_newer_condition.json
- tests/unit-tests/python/foglamp_test/common/storage/data/payload_older_condition.json
- tests/unit-tests/python/foglamp_test/common/storage/test_payload_builder.py
[FOGL-783](https://scaledb.atlassian.net/browse/FOGL-783)
**Tests O/P**
```
collected 63 items 
test_payload_builder.py::TestPayloadBuilderRead::test_select_payload[name-expected0] PASSED
test_payload_builder.py::TestPayloadBuilderRead::test_select_payload[test_input1-expected1] PASSED
test_payload_builder.py::TestPayloadBuilderRead::test_from_payload[test-expected0] PASSED
test_payload_builder.py::TestPayloadBuilderRead::test_from_payload[test, test2-expected1] PASSED
test_payload_builder.py::TestPayloadBuilderRead::test_conditions_payload[test_input0-expected0] PASSED
test_payload_builder.py::TestPayloadBuilderRead::test_conditions_payload[test_input1-expected1] PASSED
test_payload_builder.py::TestPayloadBuilderRead::test_conditions_payload[test_input2-expected2] PASSED …
```
> FOGL-783 support for newer and older conditions at payload builder side

- python/foglamp/services/core/api/browser.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_browser_assets.py
[FOGL-782](https://scaledb.atlassian.net/browse/FOGL-782)
Fixed items:
1) Where clause fixed for end points with usage of payload builder
2) Some tests are failing due to [FOGL-547](https://scaledb.atlassian.net/browse/FOGL-782), so `pytest.mark.xfail(reason="FOGL-547")`, reason for failure is format for average value has changed (string vs double) and timestamp key changed to time
Problems are mentioned in [doc](https://docs.google.com/document/d/1cECJJEslmlN4S9qRgDjszHucy4vj9HrGmqJ4En5UD2M/edit#). Especially, See point 21 and 22
**Tests O/p**
```
collected 26 items 
test_browser_assets.py::TestBrowseAssets::test_get_all_assets PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_limit PASSED …
```
> FOGL-782 browser tests are skipped with 574 

- C/plugins/storage/postgres/init.sql
- python/foglamp/plugins/north/http_translator/http_translator.py
[FOGL-805](https://scaledb.atlassian.net/browse/FOGL-805)
**How to test?**
IN _sending_process.py_ file,  translator default value set to "**http_translator**" as there is no such mechanism to pick dynamic configuration (this thing will fix by [FOGL-732](https://scaledb.atlassian.net/browse/FOGL-732))
**Syslog**
```
Dec  6 12:42:15 nerd-034 [FOGLAMP] 12-06-2017 12:42:15 - INFO :: server: foglamp.services.core.server: start core
Dec  6 12:42:15 nerd-034 [FOGLAMP] 12-06-2017 12:42:15 - INFO :: server: foglamp.services.core.server: Management API started on http://0.0.0.0:42739
Dec  6 12:42:15 nerd-034 [FOGLAMP] 12-06-2017 12:42:15 - INFO :: server: foglamp.services.core.server: start storage, from directory /home/foglamp/Development/FogLAMP/scripts
Dec  6 12:42:15 nerd-034 …
```
> FOGL-805 regression fixes for north http_translator

- C/plugins/storage/postgres/init.sql
Below error fixed
```
psql:init.sql:812: ERROR:  invalid input syntax for type json
LINE 2: ...VALUES ( 'HTTP_TR_3', 'HTTP North Plugin Configuration', ' {
^
DETAIL:  Expected string, but found "}".
CONTEXT:  JSON data, line 12: ...            "value": "http_translator",
}
```
> fixed invalid input syntax for type json - patch for FOGL-805

- tests/unit-tests/python/foglamp_test/services/core/api/test_statistics.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_statistics_history.py
**Reason for failing**: addition of **SENT_3** key in statistics
**Test O/P**
```
foglamp@nerd-034:~/Development/FogLAMP/tests/unit-tests/python/foglamp_test$ pytest -s -v services/core/api/test_statistics_history.py
platform linux -- Python 3.5.2, pytest-3.1.1, py-1.5.2, pluggy-0.4.0 -- /usr/bin/python3
cachedir: .cache
rootdir: /home/foglamp/Development/FogLAMP/tests/unit-tests/python/foglamp_test, inifile:
plugins: mock-1.6.0, cov-2.5.1, asyncio-0.6.0, allure-adaptor-1.7.7
collected 3 items 
services/core/api/test_statistics_history.py::TestStatisticsHistory::test_get_statistics_history PASSED …
```
> statistics and statistics history test fixes after the merge of PR#362

- python/foglamp/plugins/south/cc2650poll/cc2650poll.py
- python/foglamp/plugins/south/common/sensortag_cc2650.py
- python/foglamp/services/south/server.py
Addressed below:
1) Examined print statements
2) When bluetooth bad address or not really connected, it should not create any more future task etc. and should always check is_connected
3) Battery level reading added
Not addressed:
1) Up/Down Keypress as this works on notification only and not in polling. This feature will be added in async mode plugin.
2) Shutdown - FOGL-764 will take care of this. However, it has been addressed partially here.
> FOGL-812 - Native sensortag poll mode plugin improvements

- tests/unit-tests/python/foglamp_test/common/storage/test_storage_api.py
[FOGL-844](https://scaledb.atlassian.net/browse/FOGL-844) - clean up fixes as per new init.sql
```
foglamp@nerd-034:~/Development/FogLAMP/tests/unit-tests/python/foglamp_test$ pytest -s -v common/storage/test_storage_api.py
platform linux -- Python 3.5.2, pytest-3.1.1, py-1.5.2, pluggy-0.4.0 -- /usr/bin/python3
cachedir: ../../.cache
rootdir: /home/foglamp/Development/FogLAMP/tests/unit-tests/python/foglamp_test, inifile:
plugins: mock-1.6.0, cov-2.5.1, asyncio-0.6.0, allure-adaptor-1.7.7
collected 30 items 
../../common/storage/test_storage_api.py::TestStorageRead::test_select PASSED
../../common/storage/test_storage_api.py::TestStorageRead::test_ …
```
> FOGL-844 fixes

- python/foglamp/services/common/microservice_management/service_registry/monitor.py
- tests/unit-tests/python/foglamp_test/common/test_process.py
- tests/unit-tests/python/foglamp_test/common/test_service_deregister_on_fail.py
- Log 
`[FOGLAMP] 12-20-2017 14:04:13 - INFO :: monitor: SMNTR: Unregistered the failed micro-service service instance id=4fc79c7d-adf3-4445-bca9-a71f81606087: <Foo, type=Southbound, protocol=http, address=0.0.0.0, service port=40120, management port=40120, status=0>`
**Note:** I assume scheduler should wait for 5s (actually as per configured monitoring interval) before retrying restart of failed service; as heartbeat monitoring is being done every 5s per default config.
> FOGL-851 unregister the (failed) service if no ping (heartbeat) uptime

- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/browser.py
- python/foglamp/services/core/api/common.py
- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/api/scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_browser_assets.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_configuration.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_task.py
**scheduler and task api tests fixes - Fixed script directory path. As no such file directory for `scripts/foglamp`**
**REST API TESTS O/P**
```
collected 16 items 
../../tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py::TestAudit::test_get_severity PASSED
../../tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py::TestAudit::test_get_log_codes PASSED
../../tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py::TestAudit::test_get_audit PASSED
../../tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py::TestAudit::test_get_audit_with_offset PASSED
../../tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py::TestAudit::test_get_audit_by_code PASSED
../../tests/unit-tests/python/foglamp_test/services/core/api/te …
```
> Fogl 793 - camelCase convention fixes for core/api

- python/foglamp/plugins/south/cc2650poll/cc2650poll.py
- python/foglamp/services/south/server.py
@MarkRiddoch as discussed, I have modified the south service as follows:
- plugin_handle is now completely opaque. The earlier use of it in server.py is now being taken care by RuntimeError exception.
- Ingest->add_readings() from cc2560poll.py has been moved to server.py.
However, for uniformity sake, we should examine if we also need to move Ingest->add_readings() from cc2560async.py + coap_listen.py as well.
> FOGL-884 - South micro service misuses the plugin handle, Now fixed

- contrib/plugins/south/dht11pi/README.rst
- contrib/plugins/south/dht11pi/cmds.sql
- contrib/plugins/south/dht11pi/dht11pi.py
Here is a south plugin for the DHT11
It works on Raspberry Pi only
It uses the Adafruit_DHT library
It is in a new location, contrib - need to see if that s what we want
We do not have a way to install plugins at the moment, so it comes with a SQL script
> FOGL-863 - DHT11 sensor plugin for Raspberry Pi

- python/foglamp/services/core/api/scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_task.py
**Tests O/P**:
```
collected 5 items 
test_task.py::TestTask::test_cancel_task FogLAMP started.
PASSED
test_task.py::TestTask::test_get_tasks_latest FAILED
test_task.py::TestTask::test_get_tasks PASSED
test_task.py::TestTask::test_get_task PASSED
test_task.py::TestTask::test_get_state PASSED
========= 1 failed, 4 passed in 69.08 seconds =======
```
_NOTE_: One test was failing before as well, so no regression as such with new changes for the PR.
Also @MarkRiddoch please update the REST API doc for [task](https://docs.google.com/document/d/1JJDP7g25SWerNVCxgff02qp9msHbqA9nt3RAFx8-Qng/edit#heading=h.pdkhd1a1ibnb) endpoints such as **exit_code** key etc. and have a look upon the [deviations](https://docs.google.com/document/d/1cECJJEslmlN4S9qRgDjszHucy4vj9HrGmqJ4En5UD2M/edit#heading=h.dn07oy7 …
> task json response fixes as per 792 with their REST Api tests

- python/requirements.txt
Resolved to fix the error while make:
```
pip3 install -Ir python/requirements.txt --user
Double requirement given: psycopg2 (from -r python/requirements.txt (line 17)) (already in psycopg2==2.7.1 (from -r python/requirements.txt (line 3)), name='psycopg2')
```
> Removed duplicate psycopg2 requirement

- python/foglamp/common/web/middleware.py
- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/backup_restore.py
- python/foglamp/services/core/api/browser.py
- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/api/statistics.py
- python/foglamp/services/core/routes.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_audit.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_backup_restore.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_browser_assets.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_configuration.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_statistics.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_statistics_history.py
**TESTS O/P**
```
collected 22 items 
test_audit.py::TestAudit::test_get_severity PASSED
test_audit.py::TestAudit::test_get_log_codes PASSED
test_audit.py::TestAudit::test_get_audit_with_params[-6-6] PASSED
test_audit.py::TestAudit::test_get_audit_with_params[?skip=1-6-5] PASSED
test_audit.py::TestAudit::test_get_audit_with_params[?source=PURGE-4-4] PASSED
test_audit.py::TestAudit::test_get_audit_with_params[?source=PURGE&severity=error-3-3] PASSED
test_audit.py::TestAudit::test_get_audit_with_params[?source=PURGE&severity=ERROR&limit=1-3-1] PASSED
test_audit.py::TestAudit::test_get_audit_with_params[?source=PURGE&severity=INFORMATION&limit=1&skip=1-1-0] PASSED
test_audit.py::TestAudit::test_get_audit_with_params[?source=LOGGN&severity=FATAL-0-0] PASSED …
```
> FOGL-858 (Part-A)

- C/plugins/storage/postgres/init.sql
- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/routes.py
- python/foglamp/services/core/scheduler/entities.py
- python/foglamp/services/core/scheduler/scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/api/test_scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/test_scheduler.py
- tests/unit-tests/python/foglamp_test/services/core/test_scheduler_get_tasks.py
- Manually tested OK. Task related schedules being successfully enabled and disabled. Service related schedules being enabled successfully but need fixes for disabling as it requires services shutdown and unregister etc. This is blocked by **FOGL-755**.
- Automated tests ~~pending~~ added.
- Pending Testing with
> Fogl 850 - Add the ability to enable and disable schedules

- C/plugins/storage/postgres/connection.cpp
Return data from the ReadingsFetch entry point in UTC format only.
> FOGL-913 Return data in UTC format

- python/foglamp/services/common/microservice.py
- python/foglamp/services/common/microservice_management/routes.py
- python/foglamp/services/core/server.py
- tests/unit-tests/python/foglamp_test/services/core/interest_registry/test_interest_registry.py
**Tests O/p**
```
collected 17 items 
test_interest_registry.py::TestInterestRegistryApi::test_register_interest PASSED
test_interest_registry.py::TestInterestRegistryApi::test_unregister_interest PASSED
test_interest_registry.py::TestInterestRegistryApi::test_get PASSED
test_interest_registry.py::TestInterestRegistryApi::test_get_by_category PASSED
test_interest_registry.py::TestInterestRegistryApi::test_get_by_microservice_id PASSED
test_interest_registry.py::TestInterestRegistryApi::test_get_by_category_and_microservice_id PASSED
test_interest_registry.py::TestInterestRegistryApi::test_get_params_with_bad_data[-404-No interest registered] PASSED
test_interest_registry.py::TestInterestRegistryApi::test_get_params_with_bad_data[?any=123-404-No interest registered] PASSED …
```
> FOGL-930 get interest endpoint added with interest registry tests

- python/foglamp/common/jqfilter.py
- python/foglamp/plugins/north/http_north/http_north.py
- python/foglamp/plugins/north/omf/omf.py
- python/foglamp/tasks/north/sending_process.py
- tests/unit-tests/python/foglamp_test/common/test_jq_filter.py
~~Looked from http receiving side:~~
~~Earlier response (where we are manipulating each read tuple in code):~~
```
[{'asset_code': 'fogbench/pressure', 'readings': [{'reading': {'pressure': 901.3}, 'user_ts': '2018-01-11 14:13:18.157493+05:30', 'read_key': 'c452a4e1-c9ed-4023-92ee-ca37d0c354dc'}]}, {'asset_code': 'fogbench/humidity', 'readings': [{'reading': {'temperature': 20, 'humidity': 14}, 'user_ts': '2018-01-11 14:13:18.157535+05:30', 'read_key': 'd0f364e4-f43b-45cd-8553-01d0715c8a27'}]}]
```
~~Using JQ Filter:~~
```
[{'asset_code': 'fogbench/pressure', 'readings': [{'reading': {'pressure': 901.3}, 'user_ts': '2018-01-11 14:13:18.157493+05:30', 'read_key': 'c452a4e1-c9ed-4023-92ee-ca37d0c354dc'}]}, {'asset_code': 'fogbench/humidity', 'readings': [{'reading': {'temperature': 20, …
```
> FOGL-939, FOGL-940: Add JQ filter configuration on north plugins and update sending process

- python/requirements.txt
we can close https://github.com/foglamp/FogLAMP/pull/464 in favor of this
> Fix compatibility with  (aiohttp issue #2662)

- C/plugins/storage/postgres/connection.cpp
- python/foglamp/services/core/api/browser.py
- python/requirements.txt
- tests/unit-tests/C/services/storage/expected/59
- tests/unit-tests/C/services/storage/expected/60
- tests/unit-tests/C/services/storage/expected/88
- tests/unit-tests/C/services/storage/expected/89
- tests/unit-tests/C/services/storage/payloads/group_time.json
- tests/unit-tests/C/services/storage/payloads/limit_max_int.json
- tests/unit-tests/C/services/storage/payloads/skip_max_int.json
- tests/unit-tests/C/services/storage/testCleanup.sh
- tests/unit-tests/C/services/storage/testRunner.sh
- tests/unit-tests/C/services/storage/testSetup.sh
- tests/unit-tests/C/services/storage/testset
The query related to asset/value/series now returns data order by timestamp desc:
>$ curl -s 'http://localhost:8081/foglamp/asset/fogbench%2Fpressure/pressure/series' | jq
```json
[
{
"min": "804",
"average": "949.84",
"timestamp": "2018-01-15 11:10:43",
"max": "1086.5"
},
{
"min": "821.3",
"average": "911.63",
"timestamp": "2018-01-15 11:10:40",
"max": "1088.6"
},
{
"min": "812",
"average": "886.97",
"timestamp": "2018-01-15 11:10:34",
"max": "1021.9"
},
{
"min": "823.4",
"average": "958.06",
"timestamp": "2018-01-15 11:10:29",
"max": "1094.1"
}
```
> FOG-949: force ORDER BY DESC to asset/series REST API call

- python/foglamp/services/core/api/browser.py
- tests/integration/foglamp/services/core/api/test_browser_assets.py
**Tests O/p** - No regresion as such with new changes
```
collected 38 items 
test_browser_assets.py::TestBrowseAssets::test_get_all_assets PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_limit PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_sec PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_min PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_hrs PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_time_complex PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_sensor_readings PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_sensor_readings_with_empty_params …
```
> FOGL-846 summary test fixes as per FOGL-547 -min,max,avg all now string values

- python/foglamp/services/core/api/browser.py
- tests/integration/foglamp/services/core/api/test_browser_assets.py
**FOGL-547** removed from browser tests and curl examples added for asset browser end-points.
**Tests O/p**: All passed except one (xfail with reason=FOGL-510)
```
collected 38 items 
test_browser_assets.py::TestBrowseAssets::test_get_all_assets PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_limit PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_sec PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_min PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_hrs PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_readings_q_time_complex PASSED
test_browser_assets.py::TestBrowseAssets::test_get_asset_sensor_read …
```
> FOGL-846 browser time series test fixes

- python/foglamp/services/common/service_announcer.py
When Avahi is not available messages are logged in syslog...
Jan 18 10:43:08 ubuntu-test FogLAMP[5953] INFO: server: foglamp.services.core.server: Announce management API service
Jan 18 10:43:08 ubuntu-test FogLAMP[5953] ERROR: service_announcer: foglamp.services.common.service_announcer: Avahi not available, continuing without service discovery available
Jan 18 10:43:08 ubuntu-test FogLAMP[5953] INFO: server: foglamp.services.core.server: REST API Server started on http://0.0.0.0:8081
Jan 18 10:43:08 ubuntu-test FogLAMP[5953] ERROR: service_announcer: foglamp.services.common.service_announcer: Avahi not available, continuing without service discovery available
Jan 18 10:43:08 ubuntu-test FogLAMP[5953] ERROR: service_announcer: foglamp.services.common.service_announcer: Avahi not …
> FOGL-965 Make FogLAMP continue without avahi present

- .gitignore
- python/foglamp/plugins/south/cc2650async/cc2650async.py
- python/foglamp/plugins/south/cc2650poll/cc2650poll.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/core/server.py
- python/foglamp/services/south/server.py
This PR is on top of FOGL-653, though these fixes are really imp for develop branch itself (even if applied without FOGL-653)
* needs a test for http south plugin shutdown
**more improvements (may be separate JIRA)**
* needs a fix north task/ plugin shutdown/cleanup
* then check why scheduler still get timeout error (if it does even then)
* shutdown microservices (with their aiohttp instance loop) before  Or after scheduler stop
> more stop improvements and better logging for exception in scheduler

- Makefile
- scripts/core/selfssl
instead of creating certs (and temp key) and moving; create directly on the PATH decided with env var settings
> tip: use `sudo -H make install` to allow pip caching
> FOGL-966 fix 

- python/foglamp/plugins/south/cc2650async/cc2650async.py
[FOGL-972](https://scaledb.atlassian.net/browse/FOGL-972) - CC2650ASYN south plugin "reading" object format is affecting at North-side
**NOTE**: I have checked http_north plugin & omf is not tested yet as it was blocked due to [FOGL-970](https://scaledb.atlassian.net/browse/FOGL-970); as per the sending process code, now no issues with CC2650 ASYN mode with new changes with http_north plugin.
> FOGL-972 - readings object format fixes for CC2650ASYN south plugin

- tests/integration/foglamp/common/test_configuration_manager.py
As [FOGL-577](https://scaledb.atlassian.net/browse/FOGL-577), [FOGl-690](https://scaledb.atlassian.net/browse/FOGL-690) stories are fixed and out of date as of current
**Tests O/p**
```
collected 29 items 
test_configuration_manager.py::TestConfigurationManager::test_accepted_data_types PASSED
test_configuration_manager.py::TestConfigurationManager::test_create_category_keep_original_items_true PASSED
test_configuration_manager.py::TestConfigurationManager::test_create_category_keep_original_items_false PASSED
test_configuration_manager.py::TestConfigurationManager::test_create_category_with_quoted_json_data PASSED
test_configuration_manager.py::TestConfigurationManager::test_set_category_item_value_entry PASSED
test_configuration_manager.py::TestConfigurationManager::test_ …
```
> FOGL-976 removed skip/xfail annotation for configuration integration tests and use of conftest

- python/foglamp/services/core/server.py
As FOGL-933 fixed scheduler timeout error handling, let's remove this workaround
> FOGL-986 (removal of workaround) -scheduler timeouterror handling

- tests/unit/python/foglamp/plugins/south/test_http_south.py
1. fixed test and patching as add readings was never called (and, was throwing logs for task destroyed etc.) with bad request tests; 
2. using  pytest asyncio event loop fixture
3. 
```
pytest -s tests/unit/python
77 passed, 1 skipped in 0.45 seconds
```
> [#no-ticket] Fix for Unit test foglamp.plugins.south.http_south.http_south.HttpSouthIngest

- python/foglamp/common/configuration_manager.py
- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/routes.py
**curl -d '{"key":"test_cat", "description":"Test desc", "value": {"info": {"description": "Test", "type": "boolean", "default": "False"}}}' -X POST http://localhost:8081/foglamp/category**
**Response**
```
{
"key": "test_cat",
"value": {
"info": {
"value": "False",
"type": "boolean",
"description": "Test",
"default": "False"
}
},
"description": "Test desc"
}
```
**NOTE**
1) No unit tests added yet, should cover when [FOGL-1009](https://scaledb.atlassian.net/browse/FOGL-1009)
2) See Response format (not matched with DOC, as per only category name needs, but I think better to return all info)
3) create_category should not expect any return value from storage, so used *get_category_all_items* to fetch all info to make sure category has been created
**Integration tests O/p** - just to …
> FOGL-1016 create category end point added

- python/foglamp/services/core/server.py
as those are DB entries itself
And shutdown is called before unregister!
> Note: syslog entries are made by unregister core code itself hence no need to explicitly add to web endpoint def.
> FOGL-1089 exempt storage and core unregister audit log 

- python/foglamp/common/statistics.py
- tests/unit/python/foglamp/common/test_statistics.py
[FOGL-1049](https://scaledb.atlassian.net/browse/FOGL-1049)
**Coverage for /home/foglamp/Development/FogLAMP/python/foglamp/common/statistics.py : 97%**
```
38 statements   37 run 1 missing 0 excluded
```
**Tests O/P** (12/12)
```
foglamp:~/Development/FogLAMP/tests/unit/python/foglamp/common$ pytest -s -vv test_statistics.py
collected 12 items                                                                                                                            
test_statistics.py::TestStatistics::test_init_with_storage PASSED
test_statistics.py::TestStatistics::test_init_with_no_storage PASSED
test_statistics.py::TestStatistics::test_update PASSED
test_statistics.py::TestStatistics::test_update_with_invalid_params[123456-120-TypeError-key must be a string] PASSED …
```
> FOGL-1049 unit tests added for common/statistics.py with 97% code coverage

- python/foglamp/services/core/service_registry/exceptions.py
- tests/unit/python/foglamp/services/core/service_registry/test_exceptions.py
> [FOGL-1043] $ pytest tests/unit/python/foglamp/services/core/service_registry/test_exceptions.py 
```
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/foglamp/foglamp/FogLAMP, inifile:
collected 5 items                                                                                                                  
tests/unit/python/foglamp/services/core/service_registry/test_exceptions.py ....                                             [100%]
===================================================== 5 passed in 0.02 seconds …
```
> FOGL-1043 service registry package exceptions test

- tests/unit/python/foglamp/common/storage_client/test_exceptions.py
> $ pytest tests/unit/python/foglamp/common/storage_client/test_exceptions.py 
```
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/foglamp/foglamp/FogLAMP, inifile:
collected 9 items                                                                                                                  
tests/unit/python/foglamp/common/storage_client/test_exceptions.py .........                                                 [100%]
===================================================== 9 passed in 0.02 seconds …
```
> FOGL-1033 storage client exceptions test

- python/foglamp/tasks/purge/purge.py
- tests/unit/python/foglamp/plugins/common/test_plugins_common_utils.py
- tests/unit/python/foglamp/tasks/purge/test_purge_main.py
> FOGL-1063: Unit test for purge main entry point

- python/foglamp/tasks/statistics/__main__.py
- tests/unit/python/foglamp/tasks/statistics/test_statistics_main.py
**NOTE**:
We need to exclude the `if __name__ == '__main__'`  from the coverage report , of course you can do that only if you already have a test case for your main() function in your tests.
In future when we actually calculates coverage, here is [link](http://coverage.readthedocs.io/en/latest/config.html) for coverage configuration
**unit/python/foglamp suite O/P**
```
collected 187 items                                                                                                                           
common/test_audit_logger.py ..........                                                                                                  [  5%]
common/test_logger.py .....                                                                                                             [ …
```
> FOGL-1062 - statistics history main tests added

- tests/unit/python/foglamp/services/core/api/test_audit.py
**Code Coverage**: **100%** `94 statements:  94 run |  0 missing | 0 excluded`
**Tests O/P**
```
collected 17 items                                                                                                                                    
tests/unit/python/foglamp/services/core/api/test_audit.py::TestAudit::test_get_severity[pyloop] PASSED
tests/unit/python/foglamp/services/core/api/test_audit.py::TestAudit::test_audit_log_codes[pyloop] PASSED
tests/unit/python/foglamp/services/core/api/test_audit.py::TestAudit::test_get_audit_with_params[pyloop--{"where": {"column": "1", "condition": "=", "value": "1"}, "sort": {"column": "ts", "direction": "desc"}, "limit": 20}] PASSED
tests/unit/python/foglamp/services/core/api/test_audit.py::TestAudit::test_get_audit_with_params[pyloop-?source …
```
> FOGL-1006 audit rest api unit tests with code coverage 100% (PART-B)

- python/foglamp/plugins/storage/postgres/backup_restore/backup_postgres.py
- python/foglamp/services/core/api/backup_restore.py
- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
- Test Results:
`35 passed in 2.37 seconds`
- Code coverage:
```
Coverage for FogLAMP/python/foglamp/services/core/api/backup_restore.py : 100%
103 statements   103 run 0 missing 0 excluded
```
> FOGL-1007 Unit test for api/backup_restore.py

- tests/unit/python/foglamp/tasks/purge/test_purge.py
Earlier, patch for Configuration Manager, method create_category was missing, added that to ensure test has no dependency on configuration manager.
Results
16 passed in 0.18 seconds
> FOGL-1107: Part A- Fix unit test of purge.py

- tests/unit/python/foglamp/common/test_service_record.py
```
collected 7 items                                                                                                                         
tests/unit/python/foglamp/common/test_service_record.py::TestServiceRecord::test_init[None] PASSED
tests/unit/python/foglamp/common/test_service_record.py::TestServiceRecord::test_init[12] PASSED
tests/unit/python/foglamp/common/test_service_record.py::TestServiceRecord::test_init[34] PASSED
tests/unit/python/foglamp/common/test_service_record.py::TestServiceRecord::test_init_with_valid_type[Storage] PASSED
tests/unit/python/foglamp/common/test_service_record.py::TestServiceRecord::test_init_with_valid_type[Core] PASSED
tests/unit/python/foglamp/common/test_service_record.py::TestServiceRecord::test_init_with_valid_type[Southbound] PASSED …
```
> FOGL-1048 test added for Service Record

- python/foglamp/services/south/server.py
- tests/unit/python/foglamp/services/south/test_services_south_server.py
Test Result:
```
FogLAMP (FOGL-1054 *%) $ pytest -s -vv  tests/unit/python/foglamp/services/south/test_services_south_server.py 
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.5
rootdir: /home/asinha/Development/FogLAMP, inifile:
collected 15 items                                                                                                                 
tests/unit/python/foglamp/services/south/test_services_south_server.py::TestServicesSouthServer::test__start_async_plugin[pyloop] PASSED …
```
> FOGL-1054 - unit tests for services/south/server.py

- python/foglamp/common/process.py
- tests/unit/python/foglamp/common/test_process.py
Note that register_interest and unregister_interest do not have unit tests as they are currently not implemented. I have opened issue https://scaledb.atlassian.net/browse/FOGL-1119 for this.
> FOGL-1035 unit tests for FoglampProcess class

- tests/unit/python/foglamp/services/core/service_registry/test_service_registry.py
**Coverage:**
```
Name                                                                                Stmts   Miss  Cover
-------------------------------------------------------------------------------------------------------
tests/unit/python/foglamp/services/core/service_registry/test_service_registry.py      90      0   100%
```
**Test result:**
```
collected 9 items                                                                                                                         
tests/unit/python/foglamp/services/core/service_registry/test_service_registry.py::TestServiceRegistry::test_register PASSED
tests/unit/python/foglamp/services/core/service_registry/test_service_registry.py::TestServiceRegistry::test_register_with_service_port_none PASSED …
```
> FOGL-1041 service registry tests added

- python/foglamp/services/core/service_registry/service_registry.py
```
a@a ~/Development/FogLAMP/tests/unit/python/foglamp (FOGL-1133) $ pytest
platform linux -- Python 3.6.3, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/a/Development/FogLAMP/tests/unit/python/foglamp, inifile:
collected 466 items                                                                                                                
common/test_audit_logger.py ..........                                                                                       [  2%]
common/test_configuration_manager.py …
```
> FOGL-1133 - Circular import disallows many unit tests from running

- C/plugins/storage/postgres/plugin.cpp
- C/services/common/include/plugin_exception.h
- C/services/storage/storage_api.cpp
FOGL-1094: purge by size is now a not implemented feaure for Postgres
And exception is raised when purge by size is called for Postgres srorage plugin.
This has been added because the tablesize calculation is not updated after deleting records
`# curl` -v -X PUT "http://127.0.0.1:34653/storage/reading/purge?size=1&sent=0&flags=PURGE"
```
HTTP/1.1 400 Bad Request
{
"error": "Purge by size is not supported by 'Postgres' storage engine."
}
```
> FOGL-1094: purge by size is now a not implemented feaure for Postgres

- tests/unit/python/foglamp/plugins/north/http_north/test_http_north.py
**NOTE** -- Other scenarios will be tested later, as code needs refactoring in case of HTTP status codes
**Tests O/P**
```
collected 7 items                                                                                                                             
plugins/north/http_north/test_http_north.py::test_send_payload PASSED
plugins/north/http_north/test_http_north.py::test_send_bad_payload SKIPPED
plugins/north/http_north/test_http_north.py::test_send_payload_server_error SKIPPED
plugins/north/http_north/test_http_north.py::test_plugin_info PASSED
plugins/north/http_north/test_http_north.py::test_plugin_init PASSED
plugins/north/http_north/test_http_north.py::test_plugin_send[pyloop] PASSED
plugins/north/http_north/test_http_north.py::test_plugin_shutdown[pyloop] PASSED
=== 5 …
```
> FOGL-1067 http_north unit tests

- python/foglamp/services/core/api/certificate_store.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/test_certificate_store.py
Fixed items:
**Coverage 99%**
```
102 statements   | 101 run | 1 missing | 0 excluded
```
**Total tests**
```
collected 623 items
== 618 passed, 5 skipped in 32.95 seconds ==
```
**Tests O/P**
```
collected 18 items                                                                                                                            
services/core/api/test_certificate_store.py::TestCertificateStore::test_get_certs[pyloop] PASSED
services/core/api/test_certificate_store.py::TestCertificateStore::test_get_certs_if_dir_is_empty[pyloop] PASSED
services/core/api/test_certificate_store.py::TestCertificateStore::test_get_certs_if_bad_extension[pyloop] PASSED
services/core/api/test_certificate_store.py::TestCertificateStore::test_get_certs_if_pair_is_missing[pyloop] PASSED …
```
> FOGL-1132 GET end point added for cert store along with unit tests

- python/foglamp/plugins/south/cc2650poll/cc2650poll.py
- tests/unit/python/foglamp/plugins/south/cc2650poll/test_cc2650poll.py
Test result:
```
a@a ~/Development/FogLAMP (FOGL-1073) $ pytest -s -vv tests/unit/python/foglamp/plugins/south/cc2650poll/test_cc2650poll.py 
platform linux -- Python 3.6.3, pytest-3.4.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3
rootdir: /home/a/Development/FogLAMP, inifile:
collected 10 items                                                                                                                 
tests/unit/python/foglamp/plugins/south/cc2650poll/test_cc2650poll.py::test_plugin_info PASSED …
```
> Fogl 1073 - unit tests for CC2650POLL plugin

- python/foglamp/plugins/south/cc2650async/cc2650async.py
- python/foglamp/plugins/south/common/sensortag_cc2650.py
- tests/unit/python/foglamp/plugins/south/cc2650async/test_cc2650async.py
- tests/unit/python/foglamp/plugins/south/cc2650poll/test_cc2650poll.py
Test result:
```
FogLAMP (FOGL-1071 %) $ pytest -s -vv tests/unit/python/foglamp/plugins/south/cc2650async/test_cc2650async.py======================================================= test session starts ========================================================
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.5
rootdir: /home/asinha/Development/FogLAMP, inifile:
collected 8 items                                                                                                                  
tests/unit/python/foglamp/plugins/south/cc2650async/test_cc2650async.py::test_plugin_info PASSED
tests/unit/python/foglamp/plugins/south/cc2650async/test_cc26 …
```
> FOGL-1071 - unit test for CC2650ASYNC plugin

- python/foglamp/services/core/api/audit.py
- tests/unit/python/foglamp/services/core/api/test_audit.py
**Code coverage - 100%**
```
131 statements   | 131 run | 0 missing | 0 excluded
```
**Tests O/P**
```
collected 26 items                                                                                                                                    
== 26 passed in 0.85 seconds ==
```
**Test suite**
```
collected 701 items 
== 691 passed, 10 skipped in 36.77 seconds ==
```
> FOGL-1105 create audit entry tests added

- python/foglamp/common/audit_logger.py
- python/foglamp/common/storage_client/storage_client.py
- python/foglamp/services/south/ingest.py
- tests/unit/python/foglamp/common/storage_client/test_storage_client.py
> FOGL-1106 storage client raise exception on error 

- python/foglamp/services/core/api/support.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/test_support.py
**Coverage 89%**
```
35 statements   31 run || 4 missing || 0 excluded
```
**Tests O/P**
```
collected 10 items                                                                                                                            
services/core/api/test_support.py::TestBundleSupport::test_get_support_bundle[pyloop-data0-expected_content0-2] PASSED
services/core/api/test_support.py::TestBundleSupport::test_get_support_bundle[pyloop-data1-expected_content1-1] PASSED
services/core/api/test_support.py::TestBundleSupport::test_get_support_bundle[pyloop-data2-expected_content2-0] PASSED
services/core/api/test_support.py::TestBundleSupport::test_get_support_bundle[pyloop-data3-expected_content3-0] PASSED
services/core/api/test_support.py::TestBundleSupport::test_get_support_bundle_by_name[py …
```
> FOGL-1127 - Fetch support bundle functionality along with unit tests

- python/foglamp/services/core/api/statistics.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
**Tests O/P**
```
collected 8 items
= 8 passed in 0.58 seconds =
```
**Suite O/P**
```
collected 711 items
== 701 passed, 10 skipped in 34.93 seconds ==
```
> FOGL-1170 history ts format fixes for stats history

- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
**Coverage 94%**
```
79 statements   | 74 run | 5 missing | 0 excluded
```
**Test O/p**
```
collected 20 items
== 20 passed in 0.87 seconds ===
```
**Suite O/p**
```
collected 731 items
== 1 failed, 720 passed, 10 skipped in 37.51 seconds ==
```
_Note:_  1 failure for scheduler which is known bug for now
> FOGL-1009 configuration api unit tests added

- python/foglamp/plugins/south/common/sensortag_cc2650.py
- tests/unit/python/foglamp/plugins/south/common/test_sensortag_cc2650.py
Test result:
`=============================================== 24 passed, 1 skipped in 4.08 seconds ===============================================
`
Code Coverage:
```
Coverage for python/foglamp/plugins/south/common/sensortag_cc2650.py : 99% Show keyboard shortcuts
210 statements   208 run 2 missing 0 excluded
```
Suite result:
```
============================================= 746 passed, 11 skipped in 37.35 seconds ==============================================
```
> FOGL-1072 - Unit tests for SensorTagCC2650

- tests/unit/python/foglamp/services/common/test_microservice.py
Test result:
```
FogLAMP (fix_microservice_tests %) $ pytest -s -vv tests/unit/python/foglamp/services/common/test_microservice.py
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.5
rootdir: /home/asinha/Development/FogLAMP, inifile:
collected 5 items                                                                                                                  
tests/unit/python/foglamp/services/common/test_microservice.py::TestFoglampMicroservice::test_constructor_abstract_method_missing PASSED …
```
> Fixed microservice tests failing due to FOGL-1155 merger

- python/foglamp/services/core/scheduler/scheduler.py
- tests/unit/python/foglamp/services/core/scheduler/test_scheduler.py
```
tests/unit/python/foglamp/services/core/scheduler/test_scheduler.py ......s........s...........s..............s......s       [ 88%]
============================================= 746 passed, 11 skipped in 37.92 seconds ==============================================
```
> FOGL-1019, 1178 - Setting a schedule with a repeat that includes a day causes FogLAMP to fail to start

- python/foglamp/common/web/middleware.py
when verb is options, just return handler as its a preflight request to allow CORS
> fix CORS issue

- python/foglamp/services/core/support.py
service registry records are being fetched via client session to internal REST interface, hence client should be able to communicate via https scheme (and when using self signed  certificate,  we should make verify ssl false)
> FOGL-1196 fixed issue when create support bundle requested with https

- python/foglamp/common/web/middleware.py
- python/foglamp/services/core/api/common.py
- tests/unit/python/foglamp/services/core/api/test_common_ping.py
Test result:
`===================================================== 9 passed in 0.47 seconds =====================================================
`
`============================================= 883 passed, 12 skipped in 42.10 seconds ==============================================
`
**Checklist:**
> FOGL-1189 - handle Ping route based on allowPing=>True config

- python/foglamp/services/core/api/auth.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/core/user_model.py
- tests/unit/python/foglamp/services/core/api/test_auth_mandatory.py
- tests/unit/python/foglamp/services/core/api/test_auth_optional.py
- tests/unit/python/foglamp/services/core/test_user_model.py
**Tests O/P**
_auth mandatory + optional_ with **96%** code coverage
`244 statements   234 run 10 missing 0 excluded`
```
collected 85 items                                                                                                                            
== 85 passed in 4.43 seconds ==
```
**user_model** with **98%** code coverage
`188 statements   184 run 4 missing 0 excluded`
```
collected 41 items                                                                                                                            
== 40 passed, 1 skipped  in 1.16 seconds ==
```
> optional with forbidden for create, update, delete user & other enhancements

- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/scheduler/exceptions.py
- tests/unit/python/foglamp/services/core/api/test_scheduler_api.py
- tests/unit/python/foglamp/services/core/scheduler/test_scheduler_exceptions.py
No regression found for scheduler_api and exceptions tests after new changes
`pytest -s -vv services/core/api/test_scheduler_api.py`
```
collected 78 items 
== 78 passed in 4.23 seconds ===
```
`pytest -s -vv services/core/scheduler/test_scheduler_exceptions.py`
```
collected 78 items 
== 6 passed in 0.03 seconds ==
```
**Test curl examples:** (Create and Update schedule)
1) day = -1 (POST)
```
curl -d '{"type": 2, "name": "backup", "process_name": "backup", "repeat": "45", "day": -1, "time": 45678}'  -X POST  https://localhost:1995/foglamp/schedule --insecure
400: Errors in request: Day must either be None or must be an integer and in range 1-7. 
```
2) day =123 (POST)
```
curl -d '{"type": 2, "name": "backup", "process_name": "backup", "repeat": "45", "day": 123, "time": 45678}'  -X …
```
> FOGL-862 handling for day fixes when timed schedule

- python/foglamp/tasks/north/sending_process.py
value reduce to avoid the error using the new Connector Relay : 
400 {"code":1,"message":"Payload size exceeds OMF body size limit.","source":"Body","description":"Exceeded maximum allowed body size of 196608 bytes."}
> FOGL-1231 - sending_process/blockSize - value reduce

- tests/unit/python/foglamp/services/core/api/test_audit.py
- tests/unit/python/foglamp/services/core/test_user_model.py
https://scaledb.atlassian.net/browse/FOGL-1239
**Fixed tests**
**Tests O/P**
```
collected 76 items                                                                                                                                    
services/core/api/test_audit.py::TestAudit::test_get_severity[pyloop] PASSED
services/core/api/test_audit.py::TestAudit::test_audit_log_codes[pyloop] PASSED
services/core/api/test_audit.py::TestAudit::test_get_audit_with_params[pyloop--{"where": {"column": "1", "condition": "=", "value": 1}, "sort": {"column": "ts", "direction": "desc"}, "limit": 20}] PASSED
services/core/api/test_audit.py::TestAudit::test_get_audit_with_params[pyloop-?source=PURGE-{"where": {"column": "1", "condition": "=", "value": 1, "and": {"column": "code", "condition": "=", "value": …
```
> FOGL-1239 fixed audit and user model tests as per payload builder modifications 

- python/foglamp/services/core/user_model.py
- scripts/plugins/storage/postgres/init.sql
- scripts/plugins/storage/sqlite/init.sql
- tests/unit/python/foglamp/services/core/test_user_model.py
**NOTE**: We need some deep testing to make sure authentication work would not be affected.
> FOGL-1241 removed +00:00 UTC representation for user and user_login tables in sqlite and postgres will remain as with tz

- python/foglamp/common/process.py
- python/foglamp/services/common/microservice.py
- python/foglamp/services/south/ingest.py
- python/foglamp/services/south/server.py
- tests/unit/python/foglamp/services/common/test_microservice.py
- tests/unit/python/foglamp/services/south/test_ingest.py
- tests/unit/python/foglamp/services/south/test_services_south_server.py
Syslog Dump:
```
FogLAMP (FOGL-1183 *%) $ tail -f -n 10 /var/log/syslog | grep foglamp
Apr  6 16:53:12 nerd51-ThinkPad FogLAMP[23153] INFO: server: foglamp.services.core.server: start core
Apr  6 16:53:12 nerd51-ThinkPad FogLAMP[23153] INFO: server: foglamp.services.core.server: Management API started on http://0.0.0.0:37137
Apr  6 16:53:12 nerd51-ThinkPad FogLAMP[23153] INFO: server: foglamp.services.core.server: start storage, from directory /home/asinha/Development/FogLAMP/scripts
Apr  6 16:53:13 nerd51-ThinkPad FogLAMP[23153] INFO: service_registry: foglamp.services.core.service_registry.service_registry: Registered service instance id=ead450a5-f6f2-4702-b74f-035c7aab2a46: <FogLAMP Storage, type=Storage, protocol=http, address=localhost, service port=37780, management port=40824, …
```
> FOGL-1183/1111

- python/foglamp/common/configuration_manager.py
- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/api/statistics.py
- python/foglamp/services/core/scheduler/scheduler.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/services/core/api/test_audit.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
- tests/unit/python/foglamp/services/core/scheduler/test_scheduler.py
**Tests O/P**
`=== 951 passed, 12 skipped in 53.02 seconds ===`
**Tested with both storage engines**, No regression
> FOGL-1255 -Payload builder fixes for timestamp fields; ignored tz

- python/foglamp/plugins/storage/postgres/backup_restore/backup_postgres.py
- python/foglamp/plugins/storage/postgres/backup_restore/lib.py
https://scaledb.atlassian.net/browse/FOGL-1255
**Tests O/P** - No regression with this change
`== 998 passed, 13 skipped in 55.02 seconds ==`
1) curl -X GET http://localhost:8081/foglamp/backup/1
```
{
"status": "COMPLETED",
"id": 1,
"date": "2018-04-19 15:49:53.499"
}
```
2) curl -X GET http://localhost:8081/foglamp/backup
```
{
"backups": [
{
"id": 2,
"date": "2018-04-19 15:59:24.925",
"status": "RESTORED"
},
{
"id": 1,
"date": "2018-04-19 15:49:53.499",
"status": "COMPLETED"
}
]
}
```
3) curl -X GET http://localhost:8081/foglamp/backup?status=completed
```
{
"backups": [
{
"id": 1,
"date": "2018-04-19 15:49:53.499",
"status": "COMPLETED"
}
]
}
```
4) curl -X DELETE http://localhost:8081/foglamp/backup/2
```
{
"message": "Backup deleted successfully"
}
```
5) curl -X POST …
> FOGL-1255 payload builder fixes to ignore timezone for back up endpoints

- python/foglamp/services/core/scheduler/scheduler.py
The code has been tested OK for:
a) When the schedule is already enabled at the start of the foglamp server
b) When the schedule is disabled at the start of the foglamp server and is enabled afterwards
c) (a) + schedule is disabled + enabled keeping the foglamp server running
d) (b) + schedule is enabled + disabled + enabled keeping the foglamp server running
Test result:
`==================================================== 998 passed, 13 skipped in 46.43 seconds ====================================================
`
> FOGL-1274 - When enabled, Sending process tasks do not start again

- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
1) curl -X GET http://localhost:8081/foglamp/category/rest_api/authentication 
```
{
"description": "To make the authentication mandatory or optional for API calls",
"type": "string",
"default": "optional",
"value": "optional"
}
```
2) curl -X PUT -H "Content-Type: application/json" -d '{"value": "mandatory"}' http://localhost:8081/foglamp/category/rest_api/authentication
```
{
"description": "To make the authentication mandatory or optional for API calls",
"type": "string",
"default": "optional",
"value": "mandatory"
}
```
3) curl -X DELETE http://localhost:8081/foglamp/category/rest_api/authentication/value 
```
{
"description": "To make the authentication mandatory or optional for API calls",
"type": "string",
"default": "optional",
"value": "optional"
}
```
**Tests O/P** - No …
> FOGL-1265 delete configuration response fixes

- tests/unit/python/foglamp/plugins/north/omf/test_omf.py
test_plugin_transform_in_memory_data  fixed, 
it was no more working after FOGL-1277
> FOGL-1282: Fix of test_plugin_transform_in_memory_data unit test for OMF

- python/foglamp/services/core/api/statistics.py
- python/foglamp/services/core/scheduler/scheduler.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
Fixed items:
**Tests O/P** - No regression found
```
=== 1002 passed, 34 skipped in 55.53 seconds ===
```
**Code Coverage :** **100%** 
`70 statements   70 run 0 missing 0 excluded`
> FOGL-1284 value error fixes when repeat interval is more than 1 day

- python/foglamp/services/core/api/statistics.py
- python/foglamp/services/core/scheduler/scheduler.py
- tests/unit/python/foglamp/services/core/api/test_statistics_api.py
Fix works with both storage engines
**Tests O/P**
`=== 1093 passed, 13 skipped in 56.61 seconds ===`
> FOGL-1287 schedule repeat interval fixed for stats and schedule

- tests/unit/python/foglamp/plugins/north/omf/test_omf.py
``
foglamp@ubuntu:~/Development/FogLAMP$ cd /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/plugins/north/omf;\
> python3 -m pytest -v *.py
============================================= test session starts ==============================================
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
rootdir: /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/plugins/north/omf, inifile:
collected 34 items
test_omf.py::TestOMF::test_plugin_info PASSED                                                            [  2%]
test_omf.py::TestOMF::test_plugin_init_good PASSED                                                       [ …
> Fogl 1290: Extend unit tests for OMF

- python/foglamp/plugins/north/omf/omf.py
- tests/unit/python/foglamp/plugins/north/omf/test_omf.py
**Single unit test**
``
============================================= test session starts ==============================================
platform linux -- Python 3.5.2, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
rootdir: /home/foglamp/Development/FogLAMP/tests/unit/python/foglamp/plugins/north/omf, inifile:
collected 40 items
test_omf.py::TestOMF::test_plugin_info PASSED                                                            [  2%]
test_omf.py::TestOMF::test_plugin_init_good PASSED                                                       [  5%]
test_omf.py::TestOMF::test_plugin_init_bad[data0] PASSED                                                 [  7%] …
> Fogl 1294: omf north plugin should validate producerToken for empty strings

- python/foglamp/plugins/north/ocs/ocs.py
Note : No unit tests are available at the moment for OCS .
> FOGL-1305:OCS north plugin should validate producerToken and the type-id for empty strings

- extras/python/fogbench/__main__.py
- python/foglamp/plugins/common/utils.py
- python/foglamp/plugins/south/cc2650async/cc2650async.py
- python/foglamp/plugins/south/cc2650poll/cc2650poll.py
Fixed Sensortag CC2650 Async and Poll plugins to send timestamp data with local timezone info instead of UTC timezone. COAP and HTTP_SOUTH include timestamp data from source hence plugins need no such modification.
Tested OK with both Postgres and Sqlite DBs.
`============================================= 1149 passed, 13 skipped in 50.74 seconds =============================================
`
> FOGL-1313 - Fixed timestamp in Sensortag plugins to store local timezone instead of UTC timezone

- python/foglamp/services/core/api/common.py
Test Suite result:
`============================================= 1149 passed, 13 skipped in 51.32 seconds =============================================
`
syslog output:
```
May  9 16:09:06 nerd51-ThinkPad FogLAMP Storage[14951] INFO: script.plugin.storage.sqlite: SQLite 3 database '/home/asinha/Development/FogLAMP/data/foglamp.db' ready.
May  9 16:09:06 nerd51-ThinkPad FogLAMP[14968] INFO: server: foglamp.services.core.server: start core
May  9 16:09:06 nerd51-ThinkPad FogLAMP[14968] INFO: server: foglamp.services.core.server: Management API started on http://0.0.0.0:43502
May  9 16:09:06 nerd51-ThinkPad FogLAMP[14968] INFO: server: foglamp.services.core.server: start storage, from directory /home/asinha/Development/FogLAMP/scripts
May  9 16:09:06 nerd51-ThinkPad FogLAMP Storage[14975]: …
```
> FOGL-1315 - Fixed event loop running issue at foglamp stop

- python/foglamp/services/core/api/common.py
Test Suite result:
`============================================= 1149 passed, 13 skipped in 51.50 seconds =============================================
`
Syslog on Raspbian:
```
May 10 08:10:04 raspberrypi_AKS FogLAMP Storage[8261] INFO: script.plugin.storage.sqlite: SQLite 3 database '/home/pi/FogLAMP/data/foglamp.db' ready.
May 10 08:10:06 raspberrypi_AKS FogLAMP[8278] INFO: server: foglamp.services.core.server: start core
May 10 08:10:06 raspberrypi_AKS FogLAMP[8278] INFO: server: foglamp.services.core.server: Management API started on http://0.0.0.0:40961
May 10 08:10:06 raspberrypi_AKS FogLAMP[8278] INFO: server: foglamp.services.core.server: start storage, from directory /home/pi/FogLAMP/scripts
May 10 08:10:06 raspberrypi_AKS FogLAMP Storage[8297]: Connected to SQLite3 database: …
```
> FOGL-1316 - Foglamp stop error on Raspbian resolved

- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
test_backup_restore.py tests are failing on develop branch
`=== 18 failed, 20 passed, 2 warnings in 1.67 seconds ===`
So, for now skipped to avoid such noise for unit tests health, and these will be fixed  in https://scaledb.atlassian.net/browse/FOGL-1343
> tests skipped as FOGL-1322 new changes in develop

- tests/unit/python/foglamp/common/microservice_management_client/test_microservice_management_client.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/plugins/south/http_south/test_http_south.py
- tests/unit/python/foglamp/services/common/microservice_management/test_instance.py
- tests/unit/python/foglamp/services/core/api/test_audit.py
- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
- tests/unit/python/foglamp/services/core/api/test_browser_assets.py
- tests/unit/python/foglamp/services/core/api/test_common_ping.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
- tests/unit/python/foglamp/services/core/interest_registry/test_change_callback.py
- tests/unit/python/foglamp/services/core/service_registry/test_monitor.py
- tests/unit/python/foglamp/services/core/service_registry/test_service_registry.py
- tests/unit/python/foglamp/services/core/test_connect.py
- tests/unit/python/foglamp/services/south/test_services_south_server.py
**NOTE**: 
1) No syslog entries  when we run `pytest` for the python unit tests
2) No regression in tests when we run in suite as well `=== 1195 passed, 13 skipped in 67.32 seconds ==`
> Fogl-1118 - Removed log entries from python unit tests

- python/foglamp/common/process.py
- python/foglamp/common/statistics.py
- python/foglamp/services/south/ingest.py
- python/foglamp/tasks/north/sending_process.py
- python/foglamp/tasks/purge/purge.py
Replaces PR #820 which was incorrectly merged.
@ashish-jabble commented on PR #820:
```
After rebasing, I see errors and regression for statistics
ERROR: statistics: foglamp.common.statistics: Unable to update statistics value based on statistics_key DISCARDED and value_increment 0, error None#012Traceback (most recent call last):#012  File "/home/pi/FogLAMP/python/foglamp/common/statistics.py", line 71, in update#012    await self._storage.update_tbl("statistics", payload)#012  File "/home/pi/FogLAMP/python/foglamp/common/storage_client/storage_client.py", line 695, in update_tbl#012    raise ex#012  File "/home/pi/FogLAMP/python/foglamp/common/storage_client/storage_client.py", line 687, in update_tbl#012    async with self._session.put(url, data=data) as resp:#012  File …
```
> FOGL-1353 - python/foglamp/common/statistics.py should use async storage client

- tests/unit/python/foglamp/common/test_statistics.py
Test results:
`=== 18 passed in 0.72 seconds ===`
Coverage:
`FogLAMP/python/foglamp/common/statistics.py : 100%`
`72 statements   72 run 0 missing 0 excluded`
> FOGL-1392: Fix unit test common/test_statistics.py

- python/requirements-test.txt
This pull will reinstall the aiohttp dependency (2.3.8) after test-dependencies are installed.
This is required since pytest-aiohttp installs the latest version of aiohttp 3.3.1 which causes the issue:
```
E   RuntimeError: Added route will never be executed, method OPTIONS is already registered
```
while running any api test
> FOGL-1411: Reinstall aiohttp dependency in test

- python/foglamp/services/core/api/scheduler.py
- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/scheduler/scheduler.py
- python/foglamp/services/south/server.py
This PR adds below features:
-  We can now create a new schedule with "enabled" field set to "t" (or "f") and appropriate action (enable schedule in case of "t") will be initiated.
- Similarly, now any schedule can be enabled/disabled vide PUT verb with {"enabled": "t"/"f"} payload.
- Now we can create a configuration key for a service prior to its induction in the foglamp server and it will be added to the service whenever the service is added vide add_service() call. Please refer to below example.
we can create a configuration key "simplesima" even if no simplesima service is added to foglamp.
`curl -d '{"key": "simplesima", "description": "simple simulator A", "value": {"info": {"description": "Test", "type": "boolean", "default": "true"}}}' -X POST …
> FOGL-1389 - Added feature to enable/disable schedule by schedule update vide PUT

- python/foglamp/services/south/ingest.py
- python/foglamp/services/south/server.py
Tests are failing as we need to modify tests to use async storage ([FOGL-1383](https://scaledb.atlassian.net/browse/FOGL-1383)).
`======================================= 39 failed, 1182 passed, 35 skipped, 12 warnings in 97.52 seconds ========================================
`
> FOGL-1405d - Refactor ingest.py and south/server.py to improve end to end ingress and egress performance

- tests/unit/python/foglamp/services/south/test_ingest.py
- tests/unit/python/foglamp/services/south/test_services_south_server.py
Test result:
```
tests/unit/python/foglamp/plugins/north/ocs/test_ocs.py ......FF..FFF                                                                     [ 30%]
tests/unit/python/foglamp/plugins/north/omf/test_omf.py .....F..FFFFFFFFFFFFFFFF.........F......                                          [ 33%]
======================================= 23 failed, 1201 passed, 33 skipped, 11 warnings in 97.72 seconds ========================================
```
> Tests fixed which failed due to 1405d

- C/plugins/storage/sqlitememory/CMakeLists.txt
- Makefile
- python/foglamp/plugins/north/ocs/ocs.py
- python/foglamp/services/core/api/service.py
- tests/unit/python/foglamp/services/core/api/test_browser_assets.py
- tests/unit/python/foglamp/services/core/api/test_service.py
FOGL-1450 - fixed a warnings highlighted by the OMF unit tests, the problem was in the code itself not in the unit test.
```
test_ocs.py::TestOCS::test_plugin_shutdown PASSED                        [ 75%]
test_ocs.py::TestOCS::test_plugin_reconfigure PASSED                     [ 83%]
test_ocs.py::TestOCSNorthPlugin::test_create_omf_type_automatic[p_test_data0-0001-p_static_data0-pressure_typename-expected_omf_type0] PASSED [ 91%]
test_ocs.py::TestOCSNorthPlugin::test_create_omf_type_automatic[p_test_data1-0002-p_static_data1-luxometer_typename-expected_omf_type1] PASSED [100%]
========================== 12 passed in 0.13 seconds ===========================
Process finished with exit code 0
```
```
File "/home/foglamp/.local/lib/python3.5/site-packages/aiohttp/web_response.py", line 89, in …
```
> FOGL-1450 - fixed a warnings highlighted by the OMF unit tests

- docs/02_foglamp_at_a_glance.rst
- docs/03_getting_started.rst
- docs/04_installation.rst
- docs/05_testing.rst
- docs/06_plugins/01_FogLAMP_plugins.rst
- docs/06_plugins/02_writing_plugins.rst
- docs/06_plugins/03_01_DHT11.rst
- docs/06_plugins/03_south_plugins.rst
- extras/python/fogbench/__main__.py
> FOGL-1472 south plugin references fix in doc

- python/foglamp/services/core/service_registry/monitor.py
- tests/unit/python/foglamp/services/core/service_registry/test_monitor.py
The attempt to restart a failed microservice is controlled by a configuration key "restart_failed" which can be set to "manual" or "auto" mode. In "manual" mode, the service is never attempted to be restarted by the monitoring process. In "auto" mode, the monitoring process attempts to restart the microservice as soon as acquires "failed" state.
To test, please proceed as follows:
1. Start foglamp.
2. Install http-south plugin.
3. Confirm vide "curl -X GET http://localhost:8081/foglamp/service | jq" if http-south service is running.
4. Find HTTP_SOUTH processes by ps -ef | grep HTTP and kill those processes.
5. Again observe vide curl command that the status of the http-south service first changes to "unresponsive" and then to "failed".
6. It remains in "failed" state if "restart_failed" …
> FOGL-672 - Core should take action when a microservice is observed to be failed

- python/foglamp/common/common.py
- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/plugin_discovery.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
My local machine contains a few empty plugin folder. So **curl -X GET http://localhost:8081/foglamp/plugins/installed?type=south | jq** gives:
```
{
"plugins": [
{
"name": "Simple Data Simulator Async plugin",
"description": "Simple Simulator async plugin",
"version": "1.0",
"type": "south"
},
{
"name": "http_south",
"description": "HTTP South Plugin",
"version": "1.0",
"type": "south"
}
]
}
```
and **curl -X GET http://localhost:8081/foglamp/plugins/installed | jq** gives:
```
{
"plugins": [
{
"name": "OMF North",
"description": "OMF North Plugin",
"version": "1.0.0",
"type": "north"
},
{
"name": "OCS North",
"description": "OCS North Plugin",
"version": "1.0.0",
"type": "north"
},
{
"name": "Simple Data Simulator Async plugin",
"description": "Simple Simulator async plugin",
"version": …
```
> FOGL-1477 - Add API for discovery of available plugins

- python/foglamp/common/utils.py
- python/foglamp/services/core/api/task.py
- python/foglamp/services/core/routes.py
- python/foglamp/tasks/north/sending_process.py
- tests/unit/python/foglamp/services/core/api/test_task.py
Steps to test:
1. make clean, make, scripts/foglamp reset
2. Start server.
3. Check scripts/foglamp status + syslog that NO 'HTTP North' process is running.
4. In another folder, download, extract and run
[ldeploy-http-north-plugin.sh.zip](https://github.com/foglamp/FogLAMP/files/2191759/ldeploy-http-north-plugin.sh.zip). Before executing this script, please ensure that foglamp-north-http/cmds-http-north.sql contains only below commands:
```
-- SQLite only
-- Plugin loader configuration
INSERT INTO destinations ( id, description)
VALUES ( 2, 'HTTP North' );
INSERT INTO streams ( id, destination_id, description, last_object )
VALUES ( 3, 2, 'HTTP North', 0 );
-- Statistics
INSERT INTO statistics (key, description, value, previous_value)
VALUES('SENT_3', 'Readings data sent via HTTP North', …
```
> FOGL-1487 - Create a addScheduledTask REST entry point that is similar to addService

- python/foglamp/services/core/api/service.py
- tests/unit/python/foglamp/services/core/api/test_service.py
`
curl -sX POST http://localhost:8081/foglamp/service -d '{"name": "Modbus TCP", "type": "south", "plugin": "modbustcp", "enabled": true}'`
json boolean true maps  to True. And it worked in develop before 1586 last changes because
```
True == 1
True
```
> FOGL-1586 regression fix + improvement for true false handling for request.json 

- python/foglamp/common/configuration_manager.py
- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
create_category
```
curl -d '{"key": "TEST", "description": "description", "value": {"info": {"description": "Test", "type": "boolean", "default": "true"}}, "children":["rest_api"]}' -sX POST http://192.168.1.103:8081/foglamp/category | jq
{
"key": "TEST",
"description": "description",
"value": {
"info": {
"description": "Test",
"type": "boolean",
"default": "true",
"value": "true"
}
},
"children": [
"rest_api"
]
}
```
create_child_category
```
$ curl -sX POST -d '{"children" : []}' http://192.168.1.103:8081/foglamp/category/North_Statistics_to_PI/children | jq
{
"children": []
}
$ curl -sX POST -d '{"children" : []}' http://192.168.1.103:8081/foglamp/category/General/children | jq
{
"children": [
"North Readings to OCS",
"SMNTR"
]
}
$ curl -sX POST -d '{"children" : ["service"]}' …
```
> FOGL-1624 create_child category response fixes and parse unquote for category_name fields for child/parent end points

- python/foglamp/services/core/api/common.py
- python/foglamp/tasks/north/sending_process.py
- scripts/foglamp
- tests/unit/python/foglamp/services/core/api/test_common_ping.py
- tests/unit/python/foglamp/tasks/north/test_sending_process.py
3 New statistics keys are added to the statistics table. These are updated by all instances of the sending process
- Readings Sent
- Statistics Sent
- Audit Sent
The choice of which statistics is updated depends on the source of the data the sending process is sending. All readings data sent on all north bound tasks will cause "Readings Sent" to be updated. For Statistics Sent it is the statistics north from all stream and likewise for audit.
In particular the GUI should use the same statistic "Readings Sent" to display the number of readings sent to the north on the status bar at the top.
> FOGL-1627 Add master statistics keys

- python/foglamp/services/core/api/common.py
- tests/unit/python/foglamp/services/core/api/test_common_ping.py
check allowPing config only if auth is disabled (NOT mandatory).
It will not always be the case, we will cache rest_api category i.e per FOGL-1688 
*in  real production environment, http will be https (enableHttp: false) and auth enabled, i.e. authentication: mandatory*
> allowPing only when is_auth_optional is False

- python/foglamp/plugins/north/common/common.py
- python/foglamp/plugins/north/common/exceptions.py
- python/foglamp/plugins/north/pi_server/pi_server.py
- python/foglamp/tasks/north/sending_process.py
- tests/system/suites/end_to_end_PI/t/0030_prepare_PI.test
- tests/unit/python/foglamp/plugins/north/pi_server/test_pi_server.py
**Ready**
cases : 
Exceptions
```
Aug 28 11:12:09 ubuntu FogLAMP[1359] ERROR: sending_process: sending_process_North Readings to PI: cannot complete the sending operation - error details |an error occurred during the request to the destination - destination |https://WIN-4M7ODKB0RH2:5460/ingress/messages| - error details |Cannot connect to host win-4m7odkb0rh2:5460 ssl:None [Connect call failed ('192.168.1.235', 5460)]||
```
```
Aug 28 14:00:25 ubuntu FogLAMP[3023] ERROR: sending_process: sending_process_North Readings to PI: cannot complete the sending operation - error details |an error occurred during the request to the destination - destination |https://WIN-4M7ODKB0RH2:5460/ingress/messages| - error details |TimeoutError||
```
Status code 400 - type float, sending string : 
```
Aug 28 …
```
> FOGL-893-new : Sending process verbose errors if connection failed. #933

- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
```
curl -v -sX PUT http://localhost:8081/foglamp/category/North%20Readings%20to%20PI/blockSize -d '{"value":13}' | grep "HTTP/1.1"
< HTTP/1.1 400 13 should be passed in double quotes
```
> FOGL-1798 - Bad request when config item value is non-string value irrespective of the type

- python/foglamp/tasks/purge/purge.py
- tests/unit/python/foglamp/tasks/purge/test_purge.py
1)  Total count for readings with readings storage client `query` method now (As it seems to be faster than actual call)
2) For response when streams aggregated infor for min + last object like  `{'rows': [{'min_last_object': ''}], 'count': 1}`
It should be fixed from storage layer and return integer value when no data in streams table, before it was working only due to we have prerequisite entries in init.sql for stream table
3) `config['retainUnsent']['value'].lower()` - Fixed as this condition always flag value set to `retain`
4) unit tests refactored as per new change
**NOTE** - Purge by size errors are still there as no support for any of engine. See https://scaledb.atlassian.net/browse/FOGL-1301
> FOGL-1841 purge error fixes

- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/utils.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
**Note**: handling for bad python plugins already there. So, fixed for bad C-plugins. So, list of plugins we return only in case of good plugins.
Also, -ve unit tests added for both python and C type plugins
**Example:**
1) Let say we have below plugins in an evironment
```
Good south python plugins: `sinusoid, coap`
Bad south python plugins: `sensehat, envirophat` (If no external deps installed)
Good north python plugins: `pi_server`
Good south C plugins: `Random`
Bad south C plugins: `dummy` (./plugins/south/libdummy.so)
Good north C plugins: `PI_Server`
Bad north c plugins: `omf` (./plugins/north/libomf.so)
```
```
$ curl -sX GET http://localhost:8081/foglamp/plugins/installed | jq
{
"plugins": [
{
"type": "north",
"version": "1.0.0",
"description": "PI Server North Plugin",
"name": …
```
> FOGL-1839 bad plugins handling for plugin_discovery

- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/api/task.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/services/core/api/test_service.py
- tests/unit/python/foglamp/services/core/api/test_task.py
Restriction on south plugin as north task and vice-versa; 
Also restricted on plugin discovery and fixed some bad tests and new unit tests added
> FOGL-1907 - South plugin as North Task and North Plugin as South Service should not be allowed

- python/foglamp/common/microservice_management_client/microservice_management_client.py
current develop is broken, if we use a space or any such character that need url encoding, in add service. e.g. `SVC #1`, `FL 1`
With  FOGL-1872, PR #1149 use this action.
https://github.com/foglamp/FogLAMP/pull/1149/files#diff-7df07f442adb2ea900e3799bcbba7defR184
> FOGL-1872 patch | encode url for category name for create_child_category foglamp microservice client request

- python/foglamp/common/statistics.py
- python/foglamp/services/south/ingest.py
- tests/unit/python/foglamp/services/south/test_ingest.py
> FOGL-1943 Removed unused config and Avoid object instantiation on each queue ingest 

- C/tasks/north/sending_process/sending_process.cpp
per execution : 
* wait time - from 0,5 secs to up to 32 secs
* 7 messages like for example : 
```
Nov  6 15:03:03 ihsdev FogLAMP Process[718]: Sending JSON dataType message 'Type' error |Failed to send data: No route to host| - HostPort |WIN-4M7ODKB0RH2:5460| - path |/ingress/messages| - message |[{ "type": "object", "properties": { "Company": {"type": "string"}, "Location": {"type": "string"}, "Name": { "type": "string", "isindex": true } }, "classification": "static", "id": "1_sinusoid_typename_sensor" }, { "type": "object", "properties": {"sinusoid": {"type": "number", "format": "float64"}, "Time": {"type": "string", "isindex": true, "format": "date-time"}}, "classification": "dynamic", "id": "1_sinusoid_typename_measurement" }]|
```
> FOGL-2023: SP/C++ : implements a mechanism to increase the amount of the time to wait in case of a communication error

- C/common/logger.cpp
the standard mechanism requires a configuration of the syslog to have the severity (called priority)
as text and number, example : user.info, 6
the proposal is to add manually a text, so it will be available by default  without configuration.
```
sudo vi /etc/rsyslog.conf 
$template precise,"%pri-text%, %syslogpriority%,%syslogfacility%,%timegenerated%,%HOSTNAME%,%syslogtag%,%msg%\n"
$ActionFileDefaultTemplate precise
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
```
new output : 
```
user.info, 6,1,Nov  8 14:50:07,ihsdev,FogLAMP, Storage[26551]: INFO: Starting service...
user.info, 6,1,Nov  8 14:50:08,ihsdev,FogLAMP[26520], INFO: service_registry: foglamp.services.core.service_registry.service_registry: Registered service instance id=646ac7c3-3ff5-4d61-948d-405facf02d1f: …
```
> FOGL-2028: severity in the syslog

- tests/system/suites/end_to_end_PI/suite.cfg
- tests/system/suites/end_to_end_PI/t/0020_start.test
- tests/system/suites/end_to_end_PI/t/0030_prepare_PI.test
- tests/system/suites/end_to_end_PI/t/0070_read_from_PI.test
possible values for suite.cfg :  
```
export PI_SERVER=WIN-4M7ODKB0RH2
export PI_SERVER_PORT=5460
export PI_SERVER_UID=Administrator
export PI_SERVER_PWD=FogLamp200
export PI_SERVER_DATABASE=osidatabase
export CONNECTOR_RELAY_VERSION=2.x
export OMF_TYPE_ID=0010
if [[ ${CONNECTOR_RELAY_VERSION} == "1.x" ]]; then
export OMF_PRODUCER_TOKEN=omf_north_${OMF_TYPE_ID}
elif [[ ${CONNECTOR_RELAY_VERSION} == "2.x" ]]; then
export OMF_PRODUCER_TOKEN=
export OMF_PRODUCER_TOKEN='uid=5ced49c3-3a55-40e7-983f-c6cdcd5c5fd1&crt=20180620084136279&sig=GaWXZ1I4Toje3Ly9Z6/wGZ+eC6bC0Njd9bFpv3Un4QI='
fi
```
> FOGL-2037:  Change system tests to use SP/C++ instead of the SP/Python - Pi Server test suite

- scripts/extras/foglamp.sudoers
Per @Singhal-Vaibhav's [concern](https://github.com/foglamp/FogLAMP/pull/1177#pullrequestreview-174817003) noted in #1177, this PR addresses that issue. Now NOPASSWD is limited to two very specific commands, as being used in update_task.apt. This PR has been successfully tested.
> FOGL-1812-patch - NOPASSWD option further limited to 2 commands only in sudoers file

- tests/system/suites/end_to_end_OCS/suite.cfg
- tests/system/suites/end_to_end_OCS/t/0030_prepare_OCS.test
tested in a fresh clean Ubuntu 18 
Configuration used  : 
```
export PI_SERVER=WIN-4M7ODKB0RH2
export PI_SERVER_PORT=5460
export PI_SERVER_UID=Administrator
export PI_SERVER_PWD=FogLamp200
export PI_SERVER_DATABASE=osidatabase
export CONNECTOR_RELAY_VERSION=2.x
export OMF_TYPE_ID=0010
if [[ ${CONNECTOR_RELAY_VERSION} == "1.x" ]]; then
export OMF_PRODUCER_TOKEN=omf_north_${OMF_TYPE_ID}
elif [[ ${CONNECTOR_RELAY_VERSION} == "2.x" ]]; then
export OMF_PRODUCER_TOKEN=
export OMF_PRODUCER_TOKEN='uid=5ced49c3-3a55-40e7-983f-c6cdcd5c5fd1&crt=20180620084136279&sig=GaWXZ1I4Toje3Ly9Z6/wGZ+eC6bC0Njd9bFpv3Un4QI='
fi
```
```
Script Suite:     end_to_end_OCS
Suite DIR:        /home/foglamp/FogLAMP/tests/system/suites/end_to_end_OCS
Test DIR:         /home/foglamp/FogLAMP/tests/system/tests
FogLAMP Root: …
```
> Fogl 2046: Change system tests to use SP/C++ instead of the SP/Python - OCS test suite

- python/foglamp/services/core/api/configuration.py
_Steps to test:_
1) Add sine as service with below config item (make sure test config item exist in sinusoid plugin file)
```
_DEFAULT_CONFIG = {
.......,
'test': {
'description': 'T',
'type': 'script',
'default': '',
'order': '4'
}
}
```
2. Get sine configuration
```
curl -sX GET http://localhost:8081/foglamp/category/sine | jq
{
"dataPointsPerSec": {
"description": "Data points per second",
"order": "2",
"type": "integer",
"default": "1",
"value": "1"
},
"test": {
"description": "T",
"order": "4",
"type": "script",
"default": "",
"value": ""
},
"plugin": {
"type": "string",
"default": "sinusoid",
"readonly": "true",
"description": "Sinusoid Plugin",
"value": "sinusoid"
},
"assetName": {
"description": "Name of Asset",
"order": "1",
"type": "string",
"default": "sinusoid",
"value": …
```
> FOGL-1967 hexlify and unhexlify added for configuration script type value

- docs/building_foglamp/04_installation.rst
- docs/plugin_developers_guide/01_FogLAMP_plugins.rst
- docs/plugin_developers_guide/04_north_plugins.rst
From Jon Scott...
“post-installation” is written as “post-installtion” at: https://foglamp.readthedocs.io/en/master/plugin_developers_guide/01_FogLAMP_plugins.html
“The” appears twice consecutively on: https://foglamp.readthedocs.io/en/master/plugin_developers_guide/04_north_plugins.html
“Newver” instead of Newer” on: https://foglamp.readthedocs.io/en/master/building_foglamp/04_installation.html#deprecated-installing-the-snap-package
> FOG-2075 Documentation fixes

- python/foglamp/plugins/north/common/common.py
- python/foglamp/plugins/north/pi_server/pi_server.py
preview, working stage
testing cases : 
```
14	sensor_array	1a6cd43a-d316-43d9-a0d4-dd1e57221800	{"shaft1":[0.1]}	2018-11-25 10:01:01.081574+01:00	2018-11-25 16:33:28.092
15	sensor_array	1a6cd43a-d316-43d9-a0d4-dd1e57221801	{"shaft1":[0.21,0.22]}	2018-11-25 10:02:01.081574+01:00	2018-11-25 16:33:28.092
16	sensor_array	1a6cd43a-d316-43d9-a0d4-dd1e57221802	{"shaft1":[0.31,0.32,0.33]}	2018-11-25 10:03:01.081574+01:00	2018-11-25 16:33:28.092
17	sensor_array	1a6cd43a-d316-43d9-a0d4-dd1e57221803	{"shaft1":[0.11,0.12]}	2018-11-25 10:04:01.081574+01:00	2018-11-25 16:33:28.092
18	sensor_array	1a6cd43a-d316-43d9-a0d4-dd1e57221804	{"shaft1":[0.121]}	2018-11-25 10:05:01.081574+01:00	2018-11-25 16:33:28.092
19	sensor_array	1a6cd43a-d316-43d9-a0d4-dd1e57221805	{"shaft1":[-1, 0, 1, 0.121, 2.2]} …
```
> FOGL-2102: Python/OCS - Add support in SP/Python datatype for arrays of floating point numbers

- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/api/task.py
- tests/unit/python/foglamp/services/core/api/test_service.py
- tests/unit/python/foglamp/services/core/api/test_task.py
```
curl -X DELETE http://localhost:8081/foglamp/scheduled/task/T
404: T north instance does not exist.
curl -X DELETE http://localhost:8081/foglamp/service/S
404: S service name does not exist.
```
**Note:**
```
svc is None or svc.strip() == ''
```
1. Its dead code, aiohttp will take care of itself as 404
2. Code coverage improved for delete
> FOGL-2128 HTTP status code fixes on wrong service and task and tests refactored

- python/foglamp/services/core/api/south.py
**Response payload**
```
{
"name": "Sinusoid",
"address": "0.0.0.0",
"management_port": 35305,
"service_port": 35305,
"protocol": "http",
"status": "running",
"assets": [{
"count": 3373,
"asset": "sinusoid"
}],
"schedule_enabled": true
}
```
**NOTE:** 
In order to overcome the whole problem, it required changes from GUI end as well.
GUI needs to display the enabled check box on the basis of "schedule_enabled" NOT from service_registry status. Also on hover functionality from navbar?
> schedule_enabled key is added to south API to resolve FOGL-2126 issue

- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/plugin_discovery.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
```
$ curl -sX GET http://localhost:8081/foglamp/plugins/installed
{
"plugins": [{
"description": "PI Server North Plugin",
"name": "pi_server",
"type": "north",
"version": "1.0.0"
},
{
"description": "PI Server North C Plugin",
"name": "PI_Server_V2",
"type": "north",
"version": "1.0.0"
},
{
"description": "Sinusoid Plugin",
"name": "sinusoid",
"type": "south",
"version": "1.0"
},
{
"description": "Random C south plugin",
"name": "Random",
"type": "south",
"version": "1.0.0"
},
{
"description": "Scale filter plugin",
"name": "scale",
"type": "filter",
"version": "1.0.0"
},
{
"description": "Python 3.5 notification plugin",
"name": "python35",
"type": "filter",
"version": "1.0.0"
},
{
"description": "Email notification plugin",
"name": "email",
"type": "notify",
"version": "1.0.0"
},
{ …
```
> Fogl 2145 - plugin discovery API to support C-filter and C-notify plugins

- C/tasks/north/sending_process/sending_process.cpp
samples :
```
user.info, 6,1,Dec 10 15:51:47,ihsdev,FogLAMP, Process[22509]: INFO: SendingProcess loadDataThread: ('readings' stream id 4), readIdx 0, buffer is NOT empty, waiting ...
user.warning, 4,1,Dec 10 15:51:47,ihsdev,FogLAMP, Process[22509]: WARNING: SendingProcess is faster to load data than the destination to process them, so all the 10 in memory buffers are full and the load thread should wait until at least a buffer is freed.
user.info, 6,1,Dec 10 15:51:47,ihsdev,FogLAMP, Process[22509]: INFO: SendingProcess loadDataThread: ('readings' stream id 4), readIdx 2, buffer is NOT empty, waiting ...
user.warning, 4,1,Dec 10 15:51:47,ihsdev,FogLAMP, Process[22509]: WARNING: SendingProcess is faster to load data than the destination to process them, so all the 10 in memory buffers are …
```
> FOGL-2157: log added

- C/common/reading_set.cpp
- C/plugins/common/omf.cpp
this is going to solve : FOGL-2170
test case : 
```
fogbench_humidity_4	{"temperature":48,"humidity":67}	2018-12-14 23:22:09.246744+09:00
fogbench_humidity_3	{"temperature":14,"humidity":9}	2018-12-14 14:02:29.172600+00:00
fogbench_humidity_2	{"temperature":19,"humidity":8}	2018-12-13 09:00:00.001579
fogbench_humidity	{"temperature":19,"humidity":8}	2018-12-13 09:39:23.943579+01:00
``` 
```
25146	North_Readings_to_PI	2018-12-13 09:32:12.690940+01:00	0	2018-12-13 08:32:12.897
```
> FOGL-2178: fixed the mktime usage forcing the use of UTC time.

- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/filters.py
- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/api/task.py
- python/foglamp/services/core/api/utils.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/services/core/api/test_api_utils.py
- tests/unit/python/foglamp/services/core/api/test_filters.py
**Notes:**
_Area of testing with C plugins:_ `'north' | 'south' | 'filter' | 'notify' (under development, use [FOGL-1998](
https://github.com/foglamp/foglamp-notify-python35/tree/FOGL-1998))`
> FOGL-2193 C get plugin info now on the basis on the combination of directory & lib name

- tests/system/python/conftest.py
- tests/system/python/test_end_to_end_csv.py
End to end test with CSV plugin to PI written in pytest.
**Advantages of test over bash test suite:**
- Less lines of code (~190 as compared to existing bash suit > 300)
- Reusable components (conftest.py)
- Assertions at every point
- Cleanup handled, test cleans up csv created and data sent to pi and subsequent test will start with fresh environment (both at FogLAMP side and PI side)
- Execution time ~45 sec as compared to bash test suit (>2 minutes)
- Uses arg parser, test can be configured with different arguments from command line
- Junit style framework, no need for pytest wrapper as compared to bash test suite
- CI friendly (CI expects tests to be written in junit style framework)
**Usage:**
```tests/system/python $ pytest test_end_to_end_csv.py --pi_db=<pi_db_name> …
```
> FOGL-2180: system test added for end to end with csv plugin

- Makefile
- python/foglamp/services/core/api/service.py
- scripts/foglamp
- scripts/services/notification_c
- tests/unit/python/foglamp/services/core/api/test_service.py
~**Pending items**~
~- [x] make install~
~- [x] Unit tests~
~- [x] Exception handling~
**NOTE**: Notification service LIMITS to 1
**How to test?**
1) Install **foglamp-service-notification**
2) foglamp start
3) Add_service
```
curl -sX POST http://localhost:8081/foglamp/service -d '{"name": "NotificationServer", "type": "notification", "enabled": true}' | jq
{
"name": "NotificationServer",
"id": "45876056-e04c-4cde-8a82-1d8dbbbe6d72"
}
**Syslogs**
Jan  9 16:02:50 nerd-034 FogLAMP[23643] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Scheduled task for schedule 'NotificationServer' to start at 2019-01-09 16:02:50.378303
Jan  9 16:02:50 nerd-034 FogLAMP[23643] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Enabled Schedule …
```
> FOGL-2272 Ability to start the notification service via add_service REST API call

- C/services/south/ingest.cpp
stats thread was not joining main thread as it kept waiting on its condition variable even during south service shutdown.
> FOGL-2303: stats thread was not joining main thread at service shutdown

- Makefile
Default targets remain same, no change.
If you want to build foglamp keeping cache, then use:
`make USE_PIP_CACHE=yes`
> FOGL-1511: Variable for installing python requirements with/without no-cache-dir

- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/plugin_discovery.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
>  curl -sX GET http://localhost:8081/foglamp/plugins/installed?type=notify | jq
```
{
"plugins": [
{
"name": "python35",
"description": "Python 3.5 notification plugin",
"type": "notify",
"version": "1.0.0"
},
{
"name": "email",
"description": "Email notification plugin",
"type": "notify",
"version": "1.0.0"
}
]
}
```
> curl -sX GET http://localhost:8081/foglamp/plugins/installed?type=rule | jq
```
{
"plugins": [
{
"name": "OverMaxRule",
"description": "OverMaxRule  plugin",
"type": "rule",
"version": "1.0.0"
}
]
}
```
> curl -sX GET http://localhost:8081/foglamp/plugins/installed | jq
```
{
"plugins": [
{
"name": "pi_server",
"description": "PI Server North Plugin",
"type": "north",
"version": "1.0.0"
},
{
"name": "sinusoid",
"description": "Sinusoid Plugin",
"type": "south",
"version": …
```
> FOGL-2251 discovery of rule plugins added with their unit tests

- tests/system/python/README.rst
- tests/system/python/conftest.py
- tests/system/python/test_e2e_coap_OCS.py
To test:
```
FogLAMP/tests/system/python $ pytest test_e2e_coap_OCS.py --ocs-client-id="<ocs-client-id>" --ocs-client-secret="ocs-client-secret" --ocs-tenant="ocs-tenant-id" --ocs-namespace=<ocs-namespace> --ocs-token="ocs-token"
```
Console output:
```
==== test session starts =====
collected 1 item                                                                                                                                                                       
Test system/python/test_e2e_coap_OCS.py Test that data is inserted in FogLAMP and sent to OCS
start_south_north: Fixture that starts FogLAMP with south and north instance
read_data_from_ocs: Fixture to read data from OCS
Assertions:
on endpoint GET /foglamp/asset
on endpoint GET /foglamp/asset/<asset_name>
data received from OCS …
```
> FOGL-2366: Migrate end_to_end_OCS test from bash to pytest 

- tests/system/python/README.rst
- tests/system/python/conftest.py
- tests/system/python/e2e/test_e2e_coap_OCS.py
- tests/system/python/e2e/test_e2e_coap_PI.py
- tests/system/python/e2e/test_e2e_csv_PI.py
- tests/system/python/e2e/test_e2e_expr_pi.py
- tests/system/python/e2e/test_e2e_kafka.py
- tests/system/python/scripts/install_c_plugin
- tests/system/python/smoke/test_smoke.py
added directories for better organization of tests, removed plugin args from argparser as those are specific to tests, other fixes for pending TODO and FIXME
```
$ tree
.
|-- README.rst
|-- api
|-- conftest.py
|-- e2e
|   |-- test_e2e_coap_OCS.py
|   |-- test_e2e_coap_PI.py
|   |-- test_e2e_csv_PI.py
|   |-- test_e2e_expr_pi.py
|   `-- test_e2e_kafka.py
|-- pytest.ini
|-- scripts
|   |-- install_c_plugin
|   `-- install_python_plugin
`-- smoke
`-- test_smoke.py
```
> FOGL-2396 Part A

- C/plugins/storage/sqlite/connection.cpp
from the service
Note, the error message about lack of support for purge by size remains as this is an error from the plugin and is the only way this information can be communicated back to the caller.
> FOGL-2451 Make no data to purge a log message and not an error return

- python/foglamp/common/process.py
- tests/unit/python/foglamp/common/test_process.py
- tests/unit/python/foglamp/services/common/test_microservice.py
- tests/unit/python/foglamp/tasks/north/test_sending_process.py
Check with missing "--address":
```
scheduler.py
...
async def _start_task(self, schedule: _ScheduleRow) -> None:
"""Starts a task process
Raises:
EnvironmentError: If the process could not start
"""
args = self._process_scripts[schedule.process_name]
args_to_exec = args.copy()
args_to_exec.append("--port={}".format(self._core_management_port))
args_to_exec.append("--name={}".format(schedule.name))
...
...
syslog:
Feb 13 11:43:25 asinha-ThinkPad-E450 FogLAMP[12124] INFO: scheduler: foglamp.services.core.scheduler.scheduler: Process started: Schedule 'stats collection' process 'stats collector' task 30e6c9f7-12a0-426a-9ef2-b5ec070435b1 pid 12285, 1 running tasks#012['tasks/statistics', '--port=43431', '--name=stats collection']
Feb 13 11:43:25 asinha-ThinkPad-E450 FogLAMP[12286] ERROR: …
```
> FOGL-1121 - FoglampProcess should properly handle improper argument values and throw the correct exceptions

- C/plugins/storage/sqlite/connection.cpp
- C/services/storage/storage_api.cpp
Use WAL journaling mode, set sqlite cache size to 5000 pages.
Enable use of worker threads in storage service
Run purge process using worker threads
Run purge process at a low priority, yielding access when other DB threads are waiting.
> FOGL-2489: Use Sqlite WAL mode and do other performance optimizations

- C/services/south-plugin-interfaces/python/python_plugin_interface.cpp
Tested with modbustcp FOGL-2476 branch. Below errors now appear:
```
Feb 21 15:35:17 asinha-ThinkPad-E450 FogLAMP[20689] ERROR: modbustcp: foglamp.plugins.south.modbustcp.modbustcp: Failed to read data from modbus device. Got error the JSON object must be str, not 'dict'
Feb 21 15:35:17 asinha-ThinkPad-E450 Modbus TCP[20689]: ERROR: Called python script method plugin_poll : error while getting result object
Feb 21 15:35:17 asinha-ThinkPad-E450 Modbus TCP[20689]: FATAL: logErrorMessage: Error 'TypeError("the JSON object must be str, not 'dict'",)'
``` 
So we can now replace lines in all Python South Poll plugins containing 
```
except (Exception, pexpect.exceptions.TIMEOUT) as ex:
raise exceptions.DataRetrievalError(str(ex))
```
with
```
except Exception as ex:
_LOGGER.error('Failed to …
```
> FOGL-2413 - Fixed python_plugin_interface.cpp -> logErrorMessage() to correctly display exception messages

- python/foglamp/services/core/api/notification.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/test_notification.py
```
$ curl -sX GET http://localhost:8081/foglamp/notification/type | jq
{
"notification_type": [
"one shot",
"retriggered",
"toggled"
]
}
```
> FOGL-2560 GET endpoint added to return list of notification types

- tests/system/python/api/test_audit.py
**O/P**
```
$ pytest -s -vv test_audit.py 
platform linux -- Python 3.5.3, pytest-3.6.0, py-1.7.0, pluggy-0.6.0 -- /usr/local/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /home/foglamp/Development/FogLAMP/tests/system/python, inifile: pytest.ini
plugins: mock-1.10.0, cov-2.5.1, asyncio-0.8.0, allure-adaptor-1.7.10, aiohttp-0.3.0
collected 21 items                                                                                                                            
../TestAudit test_get_log_codes <- api/test_audit.py FogLAMP killed.
This script will remove all data stored in the SQLite3 datafile …
```
> FOGL-2611 audit system API tests added

- python/foglamp/services/core/server.py
- scripts/plugins/storage/sqlite.sh
```
Mar 19 13:28:52 nerd-034 FogLAMP[32427] INFO: server: foglamp.services.core.server: Loading certificates /home/foglamp/Development/FogLAMP/data/etc/certs/foglamp.cert and key /home/foglamp/Development/FogLAMP/data/etc/certs/foglamp.key
Mar 19 13:28:52 nerd-034 FogLAMP[32427] ERROR: server: foglamp.services.core.server: Certificate `foglamp` expired on Mar 18 07:44:55 2019 GMT
Mar 19 13:28:52 nerd-034 FogLAMP[32427] INFO: server: foglamp.services.core.server: Running in safe mode withOUT https on port 1995
Mar 19 13:28:52 nerd-034 FogLAMP[32427] INFO: server: foglamp.services.core.server: Announce management API service
Mar 19 13:28:52 nerd-034 FogLAMP[32427] WARNING: server: foglamp.services.core.server: A FogLAMP PID file has been found: …
```
> FOGL-2480 FogLAMP refused to start in https mode with ssl certificate expiration time

- tests/system/python/api/test_common.py
**O/P**
```
$ pytest -s -vv test_common.py 
platform linux -- Python 3.5.3, pytest-3.6.0, py-1.8.0, pluggy-0.6.0 -- /usr/local/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /home/foglamp/Development/FogLAMP/tests/system/python, inifile: pytest.ini
plugins: mock-1.10.0, cov-2.5.1, asyncio-0.8.0, allure-adaptor-1.7.10, aiohttp-0.3.0
collected 5 items                                                                                                                             
../TestCommon test_ping_default <- api/test_common.py FogLAMP killed.
This script will remove all data stored in the SQLite3 datafile …
```
> FOGL-2616 system tests added for ping, restart, shutdown added (admin api)

- tests/system/python/conftest.py
- tests/system/python/e2e/test_e2e_coap_PI.py
- tests/system/python/e2e/test_e2e_csv_PI.py
- tests/system/python/e2e/test_e2e_csv_multi_filter_pi.py
- tests/system/python/e2e/test_e2e_expr_pi.py
- tests/system/python/e2e/test_e2e_foglamp_pair.py
- tests/system/python/e2e/test_e2e_kafka.py
- tests/system/python/e2e/test_e2e_vary_asset_http_pi.py
- tests/system/python/helpers/utils.py
- tests/system/python/smoke/test_smoke.py
> FOGL-2571: Add missing assertion of verify statistics and ping in system tests

- python/foglamp/common/plugin_discovery.py
- python/foglamp/services/core/api/plugin_discovery.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
**Curl O/P**
```
$ curl -sX GET 'http://localhost:8081/foglamp/plugins/installed' | jq
{
"plugins": [
{
"name": "ocs",
"description": "OCS (OSIsoft Cloud Services) North Plugin",
"version": "1.0.0",
"type": "north"
},
{
"name": "pi_server",
"description": "PI Server North Plugin",
"version": "1.0.0",
"type": "north"
},
{
"name": "PI_Server_V2",
"description": "PI Server North C Plugin",
"version": "1.0.0",
"type": "north"
},
{
"name": "ocs_V2",
"description": "OCS (OSIsoft Cloud Services) North C Plugin",
"version": "1.0.0",
"type": "north"
},
{
"name": "coap",
"description": "CoAP Listener South Plugin",
"version": "1.5.0",
"type": "south"
},
{
"name": "email",
"description": "Email notification plugin",
"version": "1.0.0",
"type": "notificationDelivery"
},
{
"name": "OutOfBound", …
```
> FOGL-2642 fixes to find notification delivery and rule plugins in plugin_discovery API

- tests/system/python/api/test_plugin_discovery.py
- tests/system/python/scripts/install_c_plugin
- tests/system/python/scripts/reset_plugins
Verified on below environments: 
**O/P**
```
$ pytest -s -vv test_plugin_discovery.py
platform linux -- Python 3.5.3, pytest-3.6.0, py-1.8.0, pluggy-0.6.0 -- /usr/local/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /home/foglamp/Development/systemTests/FogLAMP/tests/system/python, inifile: pytest.ini
plugins: mock-1.10.0, cov-2.5.1, asyncio-0.8.0, allure-adaptor-1.7.10, aiohttp-0.3.0
collected 15 items                                                                                                                            
../TestPluginDiscovery test_cleanup <- api/test_plugin_discovery.py FogLAMP killed.
This script will remove all data …
```
> FOGL-2621 plugin discovery system tests added

- tests/system/python/api/test_service.py
- tests/system/python/conftest.py
- tests/system/python/helpers/plugin_and_service.py
- tests/system/python/plugin_and_service.py
**O/P**
```
$ pytest -s -vv test_service.py 
platform linux -- Python 3.5.3, pytest-3.6.0, py-1.8.0, pluggy-0.6.0 -- /usr/local/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /home/foglamp/Development/systemTests/FogLAMP/tests/system/python, inifile: pytest.ini
plugins: mock-1.10.0, cov-2.5.1, asyncio-0.8.0, allure-adaptor-1.7.10, aiohttp-0.3.0
collected 17 items                                                                                                                            
../TestService test_cleanup_and_setup <- api/test_service.py FogLAMP killed.
This script will remove all data stored in the SQLite3 datafile …
```
> FOGL-2623 add service system REST API tests added

- python/foglamp/common/configuration_manager.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
**Note**:  No tests required for test_conf api; as we check only exception code and type which is covered before. So only important tests are in conf manager
> FOGL-2692 Prevent update to item for which optional attribute readonly has been set to true

- tests/system/python/api/test_notification.py
- tests/system/python/e2e/test_e2e_notification_service_with_plugins.py
1. Tests added for api test of notification
2. Fixed cleanup of system test for notification
```
FogLAMP/tests/system/python/api $ pytest test_notification.py
=== 22 passed, 4 xfailed in 175.03 seconds ==
```
> FOGL-2620: Add system tests for notification REST API

- python/foglamp/common/configuration_manager.py
- python/foglamp/services/core/api/configuration.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
**Examples:**
1) Set optional filed
```
curl -X PUT -d '{"minimum": "900"}' http://localhost:8081/foglamp/category/category_name/item_name
```
2) Unsetting an optional field
```
curl -X PUT -d '{"minimum": ""}' http://localhost:8081/foglamp/category/category_name/item_name
```
**Note:** -  Validation is fairly minimal for optional attributes like minimum, maximum and length so all be numeric and maximum should be greater than minimum or vice-versa. And no link between minimum, maximum and length is needed.
> FOGL-1541 optional config items set support added with an existing enpdoint PUT category with different payload

- python/requirements.txt
**Test compatibility issues with all the other platforms we support and packaging implications of this change.**
> FOGL-2770 updated pyjq to latest version; Required for coral board

- python/foglamp/services/core/api/plugin_discovery.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
Below is the list for installed packages
```$ sudo yum list installed | grep foglamp
foglamp.x86_64                   1.6.0-1         installed                        
foglamp-south-sinusoid.x86_64    1.6.0-1         installed
```
All available packages onto system
```
1) $ curl -sX GET http://localhost:8081/foglamp/plugins/available | jq
{
"plugins": [
"foglamp-filter-asset",
"foglamp-filter-delta",
"foglamp-filter-expression",
"foglamp-filter-fft",
"foglamp-filter-metadata",
"foglamp-filter-python35",
"foglamp-filter-rate",
"foglamp-filter-rms",
"foglamp-filter-scale",
"foglamp-filter-scale-set",
"foglamp-filter-threshold",
"foglamp-gui",
"foglamp-north-http",
"foglamp-north-httpc",
"foglamp-north-kafka",
"foglamp-north-thingspeak",
"foglamp-notify-alexa",
"foglamp-notify-asset", …
```
> FOGL-2869 plugins available support added in REST API

- tests/unit/C/services/storage/postgres/testRunner.sh
- tests/unit/C/services/storage/sqlite/testRunner.sh
Forces the creation on an empty file if the output of the curl command is empty
it is needed for the behavior of the curl command in RHEL/CentOS
tested on :
* CentOS
* RHEL (in AWS)
REHL - SQLite :
REHL - Postgres:
> FOGL-2852: RHEL / CentOS: verify/fix some unit tests using Postgres/CentOS

- python/foglamp/services/core/api/plugin_discovery.py
- python/foglamp/services/core/api/plugins/common.py
- python/foglamp/services/core/api/plugins/install.py
- python/foglamp/services/core/api/service.py
- python/foglamp/services/core/routes.py
- tests/unit/python/foglamp/services/core/api/plugins/test_install.py
- tests/unit/python/foglamp/services/core/api/test_plugin_discovery_api.py
- tests/unit/python/foglamp/services/core/api/test_service.py
> FOGL-2910 - Exclude non-plugins package from GET/POST available plugins

- python/foglamp/services/core/api/plugins/common.py
**JSON file content**
```
{
"description": "A Modbus connected Flir AX8 thermal imaging camera",
"name": "FlirAX8",
"connection": "ModbusC",
"defaults": {
"map": {
"default": {
"values": [{
"name": "delta1",
"inputRegister": [1006, 1005],
"type": "float"
}]
},
"displayName": "Registered Map"
},
"protocol": {
"default": "RTU",
"readonly": "true",
"blah": "blah",
"deprecated": "true",
"displayName": "updated protocol disp",
"options": ["RTU", "TCP", "UDP"]
},
"port": {
"default": "500",
"type": "string",
"length": "6"
},
"asset": {
"default": "AX8",
"order": "12",
"displayName": "updated Asset Name disp",
"description": "Updated asset name desc"
},
"parity": {
"default": "even",
"options": ["even"],
"displayName": "updated parity disp",
"description": "Updated parity desc"
},
"plugin": { …
```
> FOGL-2888 hybrid plugins merge configuration for all fields if given instead default

- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/server.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
**Response:**
1) Category having password type returns **"****"** at ADMIN API side
```
$ curl -sX GET http://localhost:8081/foglamp/category/C1 | jq
{
"p2": {
"default": "P2",
"type": "password",
"value": "****",
"description": "P2"
},
"p1": {
"default": "P1",
"type": "password",
"value": "****",
"description": "P1"
},
"test1": {
"default": "",
"type": "script",
"value": "",
"file": "",
"description": "d"
}
}
```
2) Category having password type returns **plain text** when microservice management API
```
$ curl -sX GET http://localhost:35359/foglamp/service/category/C1 | jq
{
"p2": {
"default": "P2",
"value": "foglamp",
"type": "password",
"description": "P2"
},
"p1": {
"default": "P1",
"value": "FogLAMP",
"type": "password",
"description": "P1"
},
"test1": {
"file": "",
"default": "", …
```
> FOGL-2070 password type configuration secret text in REST API side ONLY

- C/plugins/utils/get_plugin_info.cpp
- C/services/common/include/plugin_api.h
- python/foglamp/common/plugin_discovery.py
- python/foglamp/plugins/common/utils.py
- tests/unit/python/foglamp/common/test_plugin_discovery.py
- tests/unit/python/foglamp/plugins/common/test_plugins_common_utils.py
**'flag' KEY has taken for consistency on Both sides**
**More info**
**Testing Notes:**
1) Changes in sinusoid.py file
```
@@ -123,7 +123,8 @@ def plugin_info():
'mode': 'poll',
'type': 'south',
'interface': '1.0',
-        'config': _DEFAULT_CONFIG
+        'config': _DEFAULT_CONFIG,
+        'flag': utils.DEPRECATED_BIT_MASK_VALUE
}
OR
'flag': 32
```
2) Changes in plugin.cpp for foglamp-south-csv-async
```
@@ -42,7 +42,7 @@ extern "C" {
static PLUGIN_INFORMATION info = {
PLUGIN_NAME,              // Name
VERSION,                  // Version
-       SP_ASYNC,                 // Flags
+       SP_ASYNC | SP_DEPRECATED,                 // Flags
PLUGIN_TYPE_SOUTH,        // Type
"1.0.0",                  // Interface version
CONFIG                    // Default configuration …
```
> FOGL-3000  deprecated plugin mechanism added for both C and python plugins including their unit tests

- python/foglamp/services/core/api/audit.py
- python/foglamp/services/core/api/backup_restore.py
- python/foglamp/services/core/api/configuration.py
- python/foglamp/services/core/api/support.py
- tests/unit/python/foglamp/common/test_configuration_manager.py
- tests/unit/python/foglamp/services/core/api/test_audit.py
- tests/unit/python/foglamp/services/core/api/test_backup_restore.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
- tests/unit/python/foglamp/services/core/api/test_support.py
**Verified on below env:**
**O/P for Ub1804**
```
==== 1636 passed, 42 skipped, 3 warnings in 195.16 seconds ====
```
**O/P for Rpi3 with stretch**
```
=== 1636 passed, 42 skipped, 3 warnings in 650.43 seconds ====
```
**O/P for Rpi4 with buster**
```
tests/unit/python/foglamp/services/core/api/test_common_ping.py ....EEEE..
== 1632 passed, 42 skipped, 12 warnings, 4 error in 178.85 seconds ==
```
> 500 exception handling tests fixes; fixed exception with HTTPInternalServerError instead of HTTPException

- python/foglamp/services/core/api/plugins/common.py
- python/foglamp/services/core/api/plugins/install.py
As discussed on friday scrum, we should add `sudo apt update` before fetching and on installing available packages.
1)  curl -X GET http://localhost:8081/foglamp/plugins/available
2) curl -sX POST http://localhost:8081/foglamp/plugins -d '{"format":"repository", "name": "foglamp-south-sinusoid"}'
**Use case:**
nightly [repo](http://archives.dianomic.com/nightly/ubuntu1804/x86_64/) gets updated over night
In case of any failure REST API throws a bad request 400 with an error message for below scenarios
1. Any network issues with configured source/repo list
2. On incorrect sources/repo list URL
3. Either  `sudo apt update` or `sudo apt list | grep foglamp`  failed which is used internally in code, now it will capture the standard output and standard error of the apt or or yum command …
> FOGL-3081 update source repo list configuration before fetch or install available packages

- C/common/filter_pipeline.cpp
FOGK-3146: Cleanup filters pipeline fix: use reverse order
> FOGL-3146: Cleanup filters pipeline fix: use reverse order (#1643) [1.7.0 RC]

- C/services/south/include/ingest.h
- C/services/south/ingest.cpp
being processed via that pipeline. This change introduces a new moutex
on the pipeline itself as thw qMutex is not held during the processing
of the data ingested. This allows for better ingst performance by
allowing the next queue to be filled whilst the previous queue is
processed.
> FOGL-3242 Prevent reconfiguration of the filter pipeline whilst data is

- C/common/filter_pipeline.cpp
- C/common/include/filter_pipeline.h
- C/services/south/include/ingest.h
- C/services/south/ingest.cpp
on the pipeline itself as thw qMutex is not held during the processing
of the data ingested. This allows for better ingst performance by
allowing the next queue to be filled whilst the previous queue is
processed.
> FOGL-3242 | FOGL-3245  Prevent reconfiguration of the filter pipeline whilst data is being processed and fixes of deadlock issue (1.7.0 RC) 

- python/foglamp/common/configuration_manager.py
ensure script type config item file content handling &
displayName fixes now retain after create category; as it is setting to NONE while caching on update & FOGL-3246 created
https://github.com/foglamp/FogLAMP/pull/1672
This will also solve problem mentioned in FOGL-3111
> FOGL-3243 Ensure script type config item file content handling with CacheManager (1.7.0RC)

- tests/system/python/rpi/test_e2e_rpi_ephat.py
https://github.com/foglamp/foglamp-south-envirophat/pull/32
> FOGL-3194 test - default asset prefix of enviro-pHAT changed; check stats etc. as per the new value

- tests/system/python/rpi/test_e2e_rpi_ephat.py
> FOGL-3194 system test - default asset prefix of enviro-pHAT changed; check stats etc. per that (1.7.0 RC)

- python/foglamp/services/core/api/asset_tracker.py
- python/foglamp/services/core/api/common.py
- python/foglamp/services/core/api/plugins/install.py
- python/foglamp/services/core/server.py
- tests/unit/python/foglamp/services/core/api/test_configuration.py
- tests/unit/python/foglamp/services/core/api/test_filters.py
- tests/unit/python/foglamp/services/core/api/test_scheduler_api.py
- tests/unit/python/foglamp/services/core/api/test_service.py
- tests/unit/python/foglamp/services/core/api/test_task.py
…ception and  response reason not None handling ( cherry-picked #1690)
* middleware should capture all http exceptions hence reverted this statement; in case of 500 if response reason is not there it should be asserted with empty string instead of None
* in case of 500 if response reason is not there it should be asserted with empty string instead of None
> FOGL-3039 patch / FOGL-3089 HTTPInternalServerError instead of HTTPEx… (1.7.0 RC)
